PANDAS  -> DATA CLEANING
-> DATA VISUALIZATION
-> DATA MINING
-> DATA WRANGLING

-> SERIES 1D
-> DATA FRAME  2D
-> PANEL -> 3D

1=>
PANDAS 
1.SERIES 1D
2.DATAFRAME 
3.FUNCTION


# PANDAS
IN PANDAS SERIES IN ONE DIAMENSIONAL LAVELED ARRAY OF VALUES THAT CAN BE USE REPRESENT COLUMN OF DATA IN A DATA FRAME

In [1174]:
import pandas as pd

In [1175]:
a=pd.Series([1,2.0,3,4.0,35,456],dtype='int',index=['a','b','c','d','e','f'],name='aa')

In [1176]:
a.head()

a     1
b     2
c     3
d     4
e    35
Name: aa, dtype: int64

In [1177]:
a.shape

(6,)

In [1178]:
a.ndim

1

NOW WE ARE CREATE DATA FRAME

 A DATA RAME IN THE PANDAS IN  A TWO DIAMENSIONAL OF DATA WITH ROW AND COLUMN A POTETIONALY DIFF DATA TYPE

QUE  = HOW WE CAN CREATE DATA FRAME
ANS=  BY USING DICTIONARY

In [1179]:
# DATA FRAME
dict1={'name':['sachin','khan','ayan'],'age':[12,13,14],'cgpa':[9.0,80.0,10]}
dict1

{'name': ['sachin', 'khan', 'ayan'],
 'age': [12, 13, 14],
 'cgpa': [9.0, 80.0, 10]}

In [1180]:
pd.DataFrame(dict1)

     name  age  cgpa
0  sachin   12   9.0
1    khan   13  80.0
2    ayan   14  10.0

In [1181]:
import numpy as np

In [1182]:
lst=[['sohel','saurabh','sachin'],[np.nan,5,20],[80.0,45.0,95.0]]
lst

[['sohel', 'saurabh', 'sachin'], [nan, 5, 20], [80.0, 45.0, 95.0]]

In [1183]:
pd.DataFrame(lst,index=["name","age","cgpa"]).T

      name  age  cgpa
0    sohel  NaN  80.0
1  saurabh    5  45.0
2   sachin   20  95.0

In [1184]:
tpl=(('sohel','saurabh','sachin'),(np.nan,5,20),(80.0,45.0,95.0))
tpl

(('sohel', 'saurabh', 'sachin'), (nan, 5, 20), (80.0, 45.0, 95.0))

In [1185]:
pd.DataFrame(tpl,index=['name','age','cgpa']).T

      name  age  cgpa
0    sohel  NaN  80.0
1  saurabh    5  45.0
2   sachin   20  95.0

In [1186]:
import pandas as pd
import seaborn as sns

s=pd.read_csv('data.csv')
s

,Unnamed: 0,sepal_length,sepal_width,petal_length,petal_width,species
0,0,5.1,3.5,1.4,0.2,setosa
1,1,4.9,3.0,1.4,0.2,setosa
2,2,4.7,3.2,1.3,0.2,setosa
3,3,4.6,3.1,1.5,0.2,setosa
4,4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,virginica
146,146,6.3,2.5,5.0,1.9,virginica
147,147,6.5,3.0,5.2,2.0,virginica
148,148,6.2,3.4,5.4,2.3,virginica
149,149,5.9,3.0,5.1,1.8,virginica

In [1187]:
s.head()

   Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width species
0           0           5.1          3.5           1.4          0.2  setosa
1           1           4.9          3.0           1.4          0.2  setosa
2           2           4.7          3.2           1.3          0.2  setosa
3           3           4.6          3.1           1.5          0.2  setosa
4           4           5.0          3.6           1.4          0.2  setosa

In [1188]:
s.tail()

,Unnamed: 0,sepal_length,sepal_width,petal_length,petal_width,species
145,145,6.7,3.0,5.2,2.3,virginica
146,146,6.3,2.5,5.0,1.9,virginica
147,147,6.5,3.0,5.2,2.0,virginica
148,148,6.2,3.4,5.4,2.3,virginica
149,149,5.9,3.0,5.1,1.8,virginica

In [1189]:
# num of row and num of column danga shape
s.shape

(150, 6)

In [1190]:
s.shape[0]

150

In [1191]:
s.shape[1]

6

In [1192]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    150 non-null    int64
 1   sepal_length  150 non-null    float64
 2   sepal_width   150 non-null    float64
 3   petal_length  150 non-null    float64
 4   petal_width   150 non-null    float64
 5   species       150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [1193]:
# dulicate fun batata ha
s.duplicated().sum()

np.int64(0)

In [1194]:
s['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [1195]:
s['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [1196]:
s.isnull()

     Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  species
0         False         False        False         False        False    False
1         False         False        False         False        False    False
2         False         False        False         False        False    False
3         False         False        False         False        False    False
4         False         False        False         False        False    False
..          ...           ...          ...           ...          ...      ...
145       False         False        False         False        False    False
146       False         False        False         False        False    False
147       False         False        False         False        False    False
148       False         False        False         False        False    False
149       False         False        False         False        False    False

[150 rows x 6 columns]

In [1197]:
s.isnull().sum()

Unnamed: 0      0
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [1198]:
# kisi bhi column ma null value presnt ha ki nahi 
s.describe()

       Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width
count  150.000000    150.000000   150.000000    150.000000   150.000000
mean    74.500000      5.843333     3.057333      3.758000     1.199333
std     43.445368      0.828066     0.435866      1.765298     0.762238
min      0.000000      4.300000     2.000000      1.000000     0.100000
25%     37.250000      5.100000     2.800000      1.600000     0.300000
50%     74.500000      5.800000     3.000000      4.350000     1.300000
75%    111.750000      6.400000     3.300000      5.100000     1.800000
max    149.000000      7.900000     4.400000      6.900000     2.500000

In [1199]:
s.describe(include='object')

       species
count      150
unique       3
top     setosa
freq        50

In [1200]:
df1=pd.read_csv('churn-bigml-20.csv')
df2=pd.read_csv('churn-bigml-80.csv')

In [1201]:
df1.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [1202]:
df2.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [1203]:
df1.duplicated().sum()

np.int64(0)

In [1204]:
df2.duplicated().sum()

np.int64(0)

In [1205]:
df1.drop_duplicates(inplace=True)

In [1206]:
df1.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [1207]:
df1.head(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True

In [1208]:
df1.groupby('State')['Total day charge'].mean()

State
AK    28.905556
AL    29.727857
AR    31.358750
AZ    28.310000
CA    32.340000
CO    29.232857
CT    30.349333
DC    32.231111
DE    30.589000
FL    31.494444
GA    29.020000
HI    32.625556
IA    25.235000
ID    32.706471
IL    31.646154
IN    33.191176
KS    30.295000
KY    28.768125
LA    32.843750
MA    32.876154
MD    32.115000
ME    33.293846
MI    31.720667
MN    34.356429
MO    29.280833
MS    32.399412
MT    29.872667
NC    31.200000
ND    32.306667
NE    29.745000
NH    30.037692
NJ    32.008333
NM    28.205556
NV    27.244000
NY    31.640000
OH    29.834167
OK    30.495556
OR    33.830000
PA    26.697778
RI    25.211176
SC    31.260000
SD    30.950000
TN    25.772500
TX    31.124706
UT    31.208333
VA    28.049000
VT    30.290625
WA    31.872778
WI    32.499412
WV    31.183333
WY    30.867273
Name: Total day charge, dtype: float64

In [1209]:
df1.groupby('State')['Total day charge'].sum()

State
AK    260.15
AL    416.19
AR    250.87
AZ    537.89
CA    323.40
CO    204.63
CT    455.24
DC    290.08
DE    305.89
FL    283.45
GA    145.10
HI    293.63
IA    151.41
ID    556.01
IL    411.40
IN    564.25
KS    545.31
KY    460.29
LA    525.50
MA    427.39
MD    321.15
ME    432.82
MI    475.81
MN    480.99
MO    351.37
MS    550.79
MT    448.09
NC    374.40
ND    581.52
NE    475.92
NH    390.49
NJ    576.15
NM    507.70
NV    136.22
NY    474.60
OH    358.01
OK    274.46
OR    541.28
PA    240.28
RI    428.59
SC    343.86
SD    340.45
TN    309.27
TX    529.12
UT    374.50
VA    280.49
VT    484.65
WA    573.71
WI    552.49
WV    561.30
WY    339.54
Name: Total day charge, dtype: float64

In [1210]:
df1

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,415,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
663,AL,106,408,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
664,VT,60,415,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
665,WV,159,415,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
666,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

In [1211]:
df1

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,415,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
663,AL,106,408,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
664,VT,60,415,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
665,WV,159,415,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
666,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

In [1212]:
df1.drop('Area code',inplace=True,axis=1)

In [1213]:
df1

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
663,AL,106,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
664,VT,60,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
665,WV,159,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

In [1214]:
df1

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
663,AL,106,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
664,VT,60,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
665,WV,159,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

In [1215]:
df1.columns

Index(['State', 'Account length', 'International plan', 'Voice mail plan',
       'Number vmail messages', 'Total day minutes', 'Total day calls',
       'Total day charge', 'Total eve minutes', 'Total eve calls',
       'Total eve charge', 'Total night minutes', 'Total night calls',
       'Total night charge', 'Total intl minutes', 'Total intl calls',
       'Total intl charge', 'Customer service calls', 'Churn'],
      dtype='object')

In [1216]:
df1.drop(['Total intl minutes', 'Total intl calls',
       'Total intl charge'],inplace=True,axis=1)

In [1217]:
df1

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Customer service calls,Churn
0,LA,117,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,1,False
1,IN,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,4,True
2,NY,161,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,4,True
3,SC,111,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,2,False
4,HI,49,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,2,False
663,AL,106,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,1,False
664,VT,60,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,3,False
665,WV,159,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,1,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,2,False

In [1218]:
df1

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Customer service calls,Churn
0,LA,117,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,1,False
1,IN,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,4,True
2,NY,161,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,4,True
3,SC,111,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,2,False
4,HI,49,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,2,False
663,AL,106,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,1,False
664,VT,60,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,3,False
665,WV,159,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,1,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,2,False

In [1219]:
df1[(df1['Total night charge']>15) & (df1['Total eve minutes']<31.0)]

Empty DataFrame
Columns: [State, Account length, International plan, Voice mail plan, Number vmail messages, Total day minutes, Total day calls, Total day charge, Total eve minutes, Total eve calls, Total eve charge, Total night minutes, Total night calls, Total night charge, Customer service calls, Churn]
Index: []

In [1220]:
df1[(df1['Total day calls']>150) & (df1['Total eve calls']<300)]

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Customer service calls,Churn
91,AZ,86,No,Yes,32,70.9,163,12.05,166.7,121,14.17,244.9,105,11.02,3,False
238,MI,91,No,No,0,154.4,165,26.25,168.3,121,14.31,239.9,81,10.80,5,True

In [1221]:
df1

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Customer service calls,Churn
0,LA,117,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,1,False
1,IN,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,4,True
2,NY,161,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,4,True
3,SC,111,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,2,False
4,HI,49,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,2,False
663,AL,106,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,1,False
664,VT,60,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,3,False
665,WV,159,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,1,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,2,False

In [1222]:
df3=df1[(df1['Total day minutes']>120) & (df1['Total day calls']>100)]
df3

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Customer service calls,Churn
1,IN,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,4,True
5,AK,36,No,Yes,30,146.3,128,24.87,162.5,80,13.81,129.3,109,5.82,0,False
6,MI,65,No,No,0,211.3,120,35.92,162.6,122,13.82,134.7,118,6.06,3,False
7,ID,119,No,No,0,159.1,114,27.05,231.3,117,19.66,143.2,91,6.44,5,True
8,VA,10,No,No,0,186.1,112,31.64,190.2,66,16.17,282.8,57,12.73,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,KS,57,No,No,0,158.1,117,26.88,115.2,149,9.79,182.4,92,8.21,0,False
661,CA,84,No,No,0,280.0,113,47.60,202.2,90,17.19,156.8,103,7.06,0,True
664,VT,60,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,3,False
665,WV,159,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,1,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,2,False

In [1223]:
df4=df1[(df1['Total eve minutes']>120) & (df1['Total eve minutes']<180) & (df1['International plan']=='Yes')]
df4

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Customer service calls,Churn
152,ID,83,Yes,Yes,32,94.7,111,16.10,154.4,98,13.12,200.4,109,9.02,2,False
163,WI,149,Yes,Yes,28,126.9,97,21.57,166.9,102,14.19,145.2,77,6.53,5,True
217,NY,94,Yes,No,0,243.2,109,41.34,147.0,88,12.50,94.9,99,4.27,4,False
246,MD,37,Yes,No,0,106.6,76,18.12,147.4,89,12.53,235.8,113,10.61,2,False
354,ID,138,Yes,Yes,17,225.2,116,38.28,173.4,88,14.74,145.8,99,6.56,0,False
402,MI,126,Yes,Yes,26,129.3,123,21.98,176.5,114,15.00,154.5,102,6.95,1,False
418,IL,55,Yes,No,0,269.6,121,45.83,171.7,91,14.59,219.0,98,9.86,1,False
455,IL,68,Yes,Yes,29,195.5,113,33.24,171.6,96,14.59,204.0,85,9.18,1,True
578,MN,155,Yes,No,0,250.8,146,42.64,152.5,105,12.96,148.1,104,6.66,2,False
591,MO,101,Yes,No,0,156.4,116,26.59,130.4,114,11.08,207.3,109,9.33,1,False
601,KY,64,Yes,No,0,146.7,83,24.94,148.3,91,12.61,238.6,69,10.74,3,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,2,False

In [1224]:
pd.concat([df2,df4],axis=0)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415.0,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3.0,2.70,1,False
1,OH,107,415.0,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3.0,3.70,1,False
2,NJ,137,415.0,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5.0,3.29,0,False
3,OH,84,408.0,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7.0,1.78,2,False
4,OK,75,415.0,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3.0,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,IL,68,NaN,Yes,Yes,29,195.5,113,33.24,171.6,96,14.59,204.0,85,9.18,NaN,NaN,NaN,1,True
578,MN,155,NaN,Yes,No,0,250.8,146,42.64,152.5,105,12.96,148.1,104,6.66,NaN,NaN,NaN,2,False
591,MO,101,NaN,Yes,No,0,156.4,116,26.59,130.4,114,11.08,207.3,109,9.33,NaN,NaN,NaN,1,False
601,KY,64,NaN,Yes,No,0,146.7,83,24.94,148.3,91,12.61,238.6,69,10.74,NaN,NaN,NaN,3,False
666,CT,184,NaN,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,NaN,NaN,NaN,2,False

In [1225]:
pd.concat([df3,df4],axis=0)

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Customer service calls,Churn
1,IN,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,4,True
5,AK,36,No,Yes,30,146.3,128,24.87,162.5,80,13.81,129.3,109,5.82,0,False
6,MI,65,No,No,0,211.3,120,35.92,162.6,122,13.82,134.7,118,6.06,3,False
7,ID,119,No,No,0,159.1,114,27.05,231.3,117,19.66,143.2,91,6.44,5,True
8,VA,10,No,No,0,186.1,112,31.64,190.2,66,16.17,282.8,57,12.73,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,IL,68,Yes,Yes,29,195.5,113,33.24,171.6,96,14.59,204.0,85,9.18,1,True
578,MN,155,Yes,No,0,250.8,146,42.64,152.5,105,12.96,148.1,104,6.66,2,False
591,MO,101,Yes,No,0,156.4,116,26.59,130.4,114,11.08,207.3,109,9.33,1,False
601,KY,64,Yes,No,0,146.7,83,24.94,148.3,91,12.61,238.6,69,10.74,3,False
666,CT,184,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,2,False

HOW TO HANDLE NULL VALUE
TIGNOMATRIVC FUN
OUTLIER
MERGEFUN
DEMI FUN
SPLITE FUN 
DATA FRAME
STRITE FUN

QUE =create a data frame which have 5 col  1 colum hava normally distributerd val 2 col have  inform 3 binomal 4 -19 t0 +19  5 colmn take the random val

QUE =   num of row =500 than yoy hava to creaate a data frame to all pandas operation 

QUE  = create  a data frame oy using a num py

In [1226]:
import numpy as np
import pandas as pd

In [1227]:
norm=np.random.normal(size=500)
bino=np.random.binomial(100,0.6,size=500)
unif=np.random.uniform(size=500)
_4th=np.linspace(-19,19,num=500,dtype=float)
_5th=np.random.rand(500)

In [1228]:
dict1={'1st_column':norm,'2nd_columm':bino,'3rd_column':unif,'4th_column':_4th,'5th_column':_5th}

In [1229]:
pd.DataFrame(dict1)

     1st_column  2nd_columm  3rd_column  4th_column  5th_column
0      0.917759          62    0.278705  -19.000000    0.720694
1     -0.899277          52    0.531076  -18.923848    0.357713
2      0.136794          61    0.906956  -18.847695    0.632958
3      0.953758          66    0.447797  -18.771543    0.967409
4     -0.496832          61    0.670494  -18.695391    0.327337
..          ...         ...         ...         ...         ...
495   -2.060275          57    0.598952   18.695391    0.794867
496   -0.263339          54    0.704851   18.771543    0.876150
497   -0.358825          53    0.802186   18.847695    0.574831
498    1.253535          56    0.657141   18.923848    0.828250
499   -1.403921          66    0.930132   19.000000    0.699798

[500 rows x 5 columns]

In [1230]:
list1=[2,3,4,5,6,78,8,np.nan,4,5,6,np.nan]
list2=['a','b','c','h','r','r',np.nan,np.nan,'ram','sita','hello','r']

In [1231]:
df=pd.DataFrame([list1,list2],index=['a','b']).T

In [1232]:
df.isnull().sum()

a    2
b    2
dtype: int64

In [1233]:
# we can replace the null value by mean and median if column have int and float data type.
# we  can replace the null value by mode if column have obj data type
# if any column have outlier we will replace by the mean value
#

In [1234]:
df

      a      b
0     2      a
1     3      b
2     4      c
3     5      h
4     6      r
5    78      r
6   8.0    NaN
7   NaN    NaN
8     4    ram
9     5   sita
10    6  hello
11  NaN      r

In [1235]:
mean=df['a'].mean()

In [1236]:
df['a'].fillna(df['a'].mean())
df['a'].fillna(mean)

C:\Users\HP\AppData\Local\Temp\ipykernel_22096\3526248882.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['a'].fillna(df['a'].mean())
C:\Users\HP\AppData\Local\Temp\ipykernel_22096\3526248882.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['a'].fillna(mean)

0      2.0
1      3.0
2      4.0
3      5.0
4      6.0
5     78.0
6      8.0
7     12.1
8      4.0
9      5.0
10     6.0
11    12.1
Name: a, dtype: float64

In [1237]:
median=df['a'].median()

In [1238]:
df['a'].fillna(df['a'].median())
df['a'].fillna(median)

C:\Users\HP\AppData\Local\Temp\ipykernel_22096\2558630037.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['a'].fillna(df['a'].median())
C:\Users\HP\AppData\Local\Temp\ipykernel_22096\2558630037.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['a'].fillna(median)

0      2.0
1      3.0
2      4.0
3      5.0
4      6.0
5     78.0
6      8.0
7      5.0
8      4.0
9      5.0
10     6.0
11     5.0
Name: a, dtype: float64

In [1239]:
df['a'].fillna(50)

C:\Users\HP\AppData\Local\Temp\ipykernel_22096\863431304.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['a'].fillna(50)

0      2.0
1      3.0
2      4.0
3      5.0
4      6.0
5     78.0
6      8.0
7     50.0
8      4.0
9      5.0
10     6.0
11    50.0
Name: a, dtype: float64

In [1240]:
df['b'].fillna(df['b'].mode()[0])

0         a
1         b
2         c
3         h
4         r
5         r
6         r
7         r
8       ram
9      sita
10    hello
11        r
Name: b, dtype: object

In [1241]:
df['b'].mode()

0    r
Name: b, dtype: object

In [1242]:
df['b'].fillna(df['b'].mode()[0],inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_22096\4047207697.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['b'].fillna(df['b'].mode()[0],inplace=True)

In [1243]:
df

      a      b
0     2      a
1     3      b
2     4      c
3     5      h
4     6      r
5    78      r
6   8.0      r
7   NaN      r
8     4    ram
9     5   sita
10    6  hello
11  NaN      r

In [1244]:
df.dropna(inplace=True)

In [1245]:
df

      a      b
0     2      a
1     3      b
2     4      c
3     5      h
4     6      r
5    78      r
6   8.0      r
8     4    ram
9     5   sita
10    6  hello

In [1246]:
df1=pd.read_csv('customer_data1.csv')
df2=pd.read_csv('customer_data2.csv')
df3=pd.read_csv('internet_data.csv')

In [1247]:
df3

,customerID,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1248]:
((df3['customerID']==df2['customerID']) &  (df2['customerID']==df1['customerID'])).sum()

np.int64(7043)

In [1249]:
merge_df=pd.merge(df1,df2,on='customerID',how='inner')

In [1250]:
df=pd.merge(merge_df,df3,on='customerID',how='inner')

In [1251]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   Contract          7043 non-null   object
 8   PaperlessBilling  7043 non-null   object
 9   PaymentMethod     7043 non-null   object
 10  MonthlyCharges    7043 non-null   float64
 11  TotalCharges      7043 non-null   object
 12  Churn             7043 non-null   object
 13  MultipleLines     7043 non-null   object
 14  InternetService   7043 non-null   object
 15  OnlineSecurity    7043 non-null   object
 16  OnlineBackup      7043 non-null   object
 17  DeviceProtection  7043 non-null   object
 18  TechSupport       7043 non-null   object
 19  StreamingTV       7043 non-null   object
 20  StreamingMovies   7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [1252]:
# lock method is called location based indexing
df.loc[40:45,['OnlineBackup','TechSupport','StreamingMovies']]

           OnlineBackup          TechSupport      StreamingMovies
40                  Yes                   No                   No
41                  Yes                   No                   No
42  No internet service  No internet service  No internet service
43                  Yes                  Yes                   No
44                  Yes                  Yes                   No
45                   No                   No                  Yes

In [1253]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,Yes,No,1,No,Month-to-month,Yes,Electronic check,...,29.85,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Male,0,No,No,34,Yes,One year,No,Mailed check,...,1889.5,No,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,No,No,2,Yes,Month-to-month,Yes,Mailed check,...,108.15,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,No,No,45,No,One year,No,Bank transfer (automatic),...,1840.75,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Female,0,No,No,2,Yes,Month-to-month,Yes,Electronic check,...,151.65,Yes,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,One year,Yes,Mailed check,...,1990.5,No,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,One year,Yes,Credit card (automatic),...,7362.9,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,Month-to-month,Yes,Electronic check,...,346.45,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Month-to-month,Yes,Mailed check,...,306.6,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,Male,0,No,No,66,Yes,Two year,Yes,Bank transfer (automatic),...,6844.5,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1254]:
df.loc[df['TotalCharges']==" "]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
488,4472-LVYGI,Female,0,Yes,Yes,0,No,Two year,Yes,Bank transfer (automatic),...,,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,DSL,Yes,Yes,Yes,No,Yes,Yes
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,Two year,No,Credit card (automatic),...,,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,One year,Yes,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,Yes,DSL,No,Yes,Yes,Yes,Yes,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Two year,Yes,Bank transfer (automatic),...,,No,Yes,DSL,Yes,Yes,No,Yes,No,No

In [1255]:
df.loc[df['Partner']=='Yes']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,Yes,No,1,No,Month-to-month,Yes,Electronic check,...,29.85,No,No phone service,DSL,No,Yes,No,No,No,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Month-to-month,Yes,Electronic check,...,3046.05,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes
10,9763-GRSKD,Male,0,Yes,Yes,13,Yes,Month-to-month,Yes,Mailed check,...,587.45,No,No,DSL,Yes,No,No,No,No,No
12,8091-TTVAX,Male,0,Yes,No,58,Yes,One year,No,Credit card (automatic),...,5681.1,No,Yes,Fiber optic,No,No,Yes,No,Yes,Yes
15,3655-SNQYZ,Female,0,Yes,Yes,69,Yes,Two year,No,Credit card (automatic),...,7895.15,No,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7031,3605-JISKB,Male,1,Yes,No,55,Yes,One year,No,Credit card (automatic),...,3316.1,No,Yes,DSL,Yes,Yes,No,No,No,No
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,One year,Yes,Mailed check,...,1990.5,No,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,One year,Yes,Credit card (automatic),...,7362.9,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,Month-to-month,Yes,Electronic check,...,346.45,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Month-to-month,Yes,Mailed check,...,306.6,Yes,Yes,Fiber optic,No,No,No,No,No,No

In [1256]:
df.loc[df['tenure'] >50]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
9,6388-TABGU,Male,0,No,Yes,62,Yes,One year,No,Bank transfer (automatic),...,3487.95,No,No,DSL,Yes,Yes,No,No,No,No
12,8091-TTVAX,Male,0,Yes,No,58,Yes,One year,No,Credit card (automatic),...,5681.1,No,Yes,Fiber optic,No,No,Yes,No,Yes,Yes
15,3655-SNQYZ,Female,0,Yes,Yes,69,Yes,Two year,No,Credit card (automatic),...,7895.15,No,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes
16,8191-XWSZG,Female,0,No,No,52,Yes,One year,No,Mailed check,...,1022.95,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
17,9959-WOFKT,Male,0,No,Yes,71,Yes,Two year,No,Bank transfer (automatic),...,7382.25,No,Yes,Fiber optic,Yes,No,Yes,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7031,3605-JISKB,Male,1,Yes,No,55,Yes,One year,No,Credit card (automatic),...,3316.1,No,Yes,DSL,Yes,Yes,No,No,No,No
7034,0639-TSIQW,Female,0,No,No,67,Yes,Month-to-month,Yes,Credit card (automatic),...,6886.25,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,No
7037,2569-WGERO,Female,0,No,No,72,Yes,Two year,Yes,Bank transfer (automatic),...,1419.4,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,One year,Yes,Credit card (automatic),...,7362.9,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,Two year,Yes,Bank transfer (automatic),...,6844.5,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1257]:
df.loc[df['gender']=='Male']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
1,5575-GNVDE,Male,0,No,No,34,Yes,One year,No,Mailed check,...,1889.5,No,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,No,No,2,Yes,Month-to-month,Yes,Mailed check,...,108.15,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,No,No,45,No,One year,No,Bank transfer (automatic),...,1840.75,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Month-to-month,Yes,Credit card (automatic),...,1949.4,No,Yes,Fiber optic,No,Yes,No,No,Yes,No
9,6388-TABGU,Male,0,No,Yes,62,Yes,One year,No,Bank transfer (automatic),...,3487.95,No,No,DSL,Yes,Yes,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7033,9767-FFLEM,Male,0,No,No,38,Yes,Month-to-month,Yes,Credit card (automatic),...,2625.25,No,No,Fiber optic,No,No,No,No,No,No
7035,8456-QDAVC,Male,0,No,No,19,Yes,Month-to-month,Yes,Bank transfer (automatic),...,1495.1,No,No,Fiber optic,No,No,No,No,Yes,No
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,One year,Yes,Mailed check,...,1990.5,No,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Month-to-month,Yes,Mailed check,...,306.6,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,Male,0,No,No,66,Yes,Two year,Yes,Bank transfer (automatic),...,6844.5,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1258]:
df.loc[df['TotalCharges']==" "]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
488,4472-LVYGI,Female,0,Yes,Yes,0,No,Two year,Yes,Bank transfer (automatic),...,,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,DSL,Yes,Yes,Yes,No,Yes,Yes
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,Two year,No,Credit card (automatic),...,,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,One year,Yes,Mailed check,...,,No,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Two year,No,Mailed check,...,,No,Yes,DSL,No,Yes,Yes,Yes,Yes,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Two year,Yes,Bank transfer (automatic),...,,No,Yes,DSL,Yes,Yes,No,Yes,No,No

In [1259]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')

In [1260]:
df['TotalCharges'].isnull().sum()

np.int64(11)

In [1261]:
df1=df
df1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,Yes,No,1,No,Month-to-month,Yes,Electronic check,...,29.85,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Male,0,No,No,34,Yes,One year,No,Mailed check,...,1889.50,No,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,No,No,2,Yes,Month-to-month,Yes,Mailed check,...,108.15,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,No,No,45,No,One year,No,Bank transfer (automatic),...,1840.75,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Female,0,No,No,2,Yes,Month-to-month,Yes,Electronic check,...,151.65,Yes,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,One year,Yes,Mailed check,...,1990.50,No,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,One year,Yes,Credit card (automatic),...,7362.90,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,Month-to-month,Yes,Electronic check,...,346.45,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Month-to-month,Yes,Mailed check,...,306.60,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,Male,0,No,No,66,Yes,Two year,Yes,Bank transfer (automatic),...,6844.50,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1262]:
df['PhoneService'].unique()

array(['No', 'Yes'], dtype=object)

In [1263]:
def zero_one(x):
    if x=='Yes':
        return 1
    else:
        return 0

In [1264]:
df['Partner']=df['Partner'].apply(zero_one)

In [1265]:
   
df=pd.DataFrame({'value':[10,12,13,14,11,400,14,13,10,9,600,500,28,5,65]})
# def outlier(df,'x')
Q1=df['value'].quantile(0.25)
Q3=df['value'].quantile(0.75)
iqr=Q3-Q1

lower=Q1-1.5*iqr
upper=Q3+1.5*iqr
outlier=df[(df['value']<lower) | (df['value']>upper)]

outlier

    value
5     400
10    600
11    500

In [1266]:
len(outlier)

3

In [1267]:
df=pd.DataFrame({'value':[10,12,13,14,11,400,14,13,10,9,600,500,28,5,65]})

Q1=df['value'].quantile(0.25)
Q3=df['value'].quantile(0.75)

iqr=Q3-Q1

lower=Q1-1.5*iqr
upper=Q3+1.5*iqr
mean_value=df[(df['value']>=lower) & (df['value']<=upper)]['value'].mean()
df['value']=df['value'].apply(lambda x: mean_value if  x < lower or x > upper else x)

In [1268]:
df

    value
0    10.0
1    12.0
2    13.0
3    14.0
4    11.0
5    17.0
6    14.0
7    13.0
8    10.0
9     9.0
10   17.0
11   17.0
12   28.0
13    5.0
14   65.0

In [1269]:
print(upper,lower,mean_value)

100.5 -43.5 17.0

In [1270]:
df2

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [1271]:
df2['PhoneService'].unique()

array(['No', 'Yes'], dtype=object)

In [1272]:
df1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,1,No,1,No,Month-to-month,Yes,Electronic check,...,29.85,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Male,0,0,No,34,Yes,One year,No,Mailed check,...,1889.50,No,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,0,No,2,Yes,Month-to-month,Yes,Mailed check,...,108.15,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,0,No,45,No,One year,No,Bank transfer (automatic),...,1840.75,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Female,0,0,No,2,Yes,Month-to-month,Yes,Electronic check,...,151.65,Yes,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,1,Yes,24,Yes,One year,Yes,Mailed check,...,1990.50,No,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Female,0,1,Yes,72,Yes,One year,Yes,Credit card (automatic),...,7362.90,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,Female,0,1,Yes,11,No,Month-to-month,Yes,Electronic check,...,346.45,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Male,1,1,No,4,Yes,Month-to-month,Yes,Mailed check,...,306.60,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,Male,0,0,No,66,Yes,Two year,Yes,Bank transfer (automatic),...,6844.50,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1273]:
def zero_one(x):
    if x=='Yes':
        return 1
    else:
        return 0

In [1274]:
df1['Partner']=df1['Partner'].apply(zero_one)

In [1275]:
df1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,0,No,1,No,Month-to-month,Yes,Electronic check,...,29.85,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Male,0,0,No,34,Yes,One year,No,Mailed check,...,1889.50,No,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,0,No,2,Yes,Month-to-month,Yes,Mailed check,...,108.15,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,0,No,45,No,One year,No,Bank transfer (automatic),...,1840.75,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Female,0,0,No,2,Yes,Month-to-month,Yes,Electronic check,...,151.65,Yes,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,0,Yes,24,Yes,One year,Yes,Mailed check,...,1990.50,No,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Female,0,0,Yes,72,Yes,One year,Yes,Credit card (automatic),...,7362.90,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,Female,0,0,Yes,11,No,Month-to-month,Yes,Electronic check,...,346.45,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Male,1,0,No,4,Yes,Month-to-month,Yes,Mailed check,...,306.60,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,Male,0,0,No,66,Yes,Two year,Yes,Bank transfer (automatic),...,6844.50,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1276]:
df1['gender'].unique()
df1['gender']=df1['gender'].map({'Female':1,'Male':0})
df1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,1,0,0,No,1,No,Month-to-month,Yes,Electronic check,...,29.85,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,0,0,0,No,34,Yes,One year,No,Mailed check,...,1889.50,No,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,0,0,0,No,2,Yes,Month-to-month,Yes,Mailed check,...,108.15,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,0,0,0,No,45,No,One year,No,Bank transfer (automatic),...,1840.75,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,1,0,0,No,2,Yes,Month-to-month,Yes,Electronic check,...,151.65,Yes,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,0,Yes,24,Yes,One year,Yes,Mailed check,...,1990.50,No,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,1,0,0,Yes,72,Yes,One year,Yes,Credit card (automatic),...,7362.90,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,1,0,0,Yes,11,No,Month-to-month,Yes,Electronic check,...,346.45,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,0,1,0,No,4,Yes,Month-to-month,Yes,Mailed check,...,306.60,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,0,0,0,No,66,Yes,Two year,Yes,Bank transfer (automatic),...,6844.50,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [1277]:
def sohel(i):
    if i=='No':
        return 0
    else:
        return 1

In [1278]:
col=['PhoneService','Dependents','PaperlessBilling','Churn','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport']
for i in col:
    df1[i]=df1[i].apply(sohel)
df1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,1,0,0,0,1,0,Month-to-month,1,Electronic check,...,29.85,0,No phone service,DSL,0,1,0,0,No,No
1,5575-GNVDE,0,0,0,0,34,1,One year,0,Mailed check,...,1889.50,0,No,DSL,1,0,1,0,No,No
2,3668-QPYBK,0,0,0,0,2,1,Month-to-month,1,Mailed check,...,108.15,1,No,DSL,1,1,0,0,No,No
3,7795-CFOCW,0,0,0,0,45,0,One year,0,Bank transfer (automatic),...,1840.75,0,No phone service,DSL,1,0,1,1,No,No
4,9237-HQITU,1,0,0,0,2,1,Month-to-month,1,Electronic check,...,151.65,1,No,Fiber optic,0,0,0,0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,0,1,24,1,One year,1,Mailed check,...,1990.50,0,Yes,DSL,1,0,1,1,Yes,Yes
7039,2234-XADUH,1,0,0,1,72,1,One year,1,Credit card (automatic),...,7362.90,0,Yes,Fiber optic,0,1,1,0,Yes,Yes
7040,4801-JZAZL,1,0,0,1,11,0,Month-to-month,1,Electronic check,...,346.45,0,No phone service,DSL,1,0,0,0,No,No
7041,8361-LTMKD,0,1,0,0,4,1,Month-to-month,1,Mailed check,...,306.60,1,Yes,Fiber optic,0,0,0,0,No,No
7042,3186-AJIEK,0,0,0,0,66,1,Two year,1,Bank transfer (automatic),...,6844.50,0,No,Fiber optic,1,0,1,1,Yes,Yes

In [1279]:
df=df1
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,...,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,1,0,0,0,1,0,Month-to-month,1,Electronic check,...,29.85,0,No phone service,DSL,0,1,0,0,No,No
1,5575-GNVDE,0,0,0,0,34,1,One year,0,Mailed check,...,1889.50,0,No,DSL,1,0,1,0,No,No
2,3668-QPYBK,0,0,0,0,2,1,Month-to-month,1,Mailed check,...,108.15,1,No,DSL,1,1,0,0,No,No
3,7795-CFOCW,0,0,0,0,45,0,One year,0,Bank transfer (automatic),...,1840.75,0,No phone service,DSL,1,0,1,1,No,No
4,9237-HQITU,1,0,0,0,2,1,Month-to-month,1,Electronic check,...,151.65,1,No,Fiber optic,0,0,0,0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,0,1,24,1,One year,1,Mailed check,...,1990.50,0,Yes,DSL,1,0,1,1,Yes,Yes
7039,2234-XADUH,1,0,0,1,72,1,One year,1,Credit card (automatic),...,7362.90,0,Yes,Fiber optic,0,1,1,0,Yes,Yes
7040,4801-JZAZL,1,0,0,1,11,0,Month-to-month,1,Electronic check,...,346.45,0,No phone service,DSL,1,0,0,0,No,No
7041,8361-LTMKD,0,1,0,0,4,1,Month-to-month,1,Mailed check,...,306.60,1,Yes,Fiber optic,0,0,0,0,No,No
7042,3186-AJIEK,0,0,0,0,66,1,Two year,1,Bank transfer (automatic),...,6844.50,0,No,Fiber optic,1,0,1,1,Yes,Yes

In [1280]:
df=df.select_dtypes(include='object')
df.drop(['customerID','Contract'],axis=1,inplace=True)

In [1281]:
df

,PaymentMethod,MultipleLines,InternetService,StreamingTV,StreamingMovies
0,Electronic check,No phone service,DSL,No,No
1,Mailed check,No,DSL,No,No
2,Mailed check,No,DSL,No,No
3,Bank transfer (automatic),No phone service,DSL,No,No
4,Electronic check,No,Fiber optic,No,No
...,...,...,...,...,...
7038,Mailed check,Yes,DSL,Yes,Yes
7039,Credit card (automatic),Yes,Fiber optic,Yes,Yes
7040,Electronic check,No phone service,DSL,No,No
7041,Mailed check,Yes,Fiber optic,No,No
7042,Bank transfer (automatic),No,Fiber optic,Yes,Yes

In [1282]:
df['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [1283]:
df['MultipleLines'].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [1284]:
df1=df1.select_dtypes(exclude='object')
df1

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport
0,1,0,0,0,1,0,1,29.85,29.85,0,0,1,0,0
1,0,0,0,0,34,1,0,56.95,1889.50,0,1,0,1,0
2,0,0,0,0,2,1,1,53.85,108.15,1,1,1,0,0
3,0,0,0,0,45,0,0,42.30,1840.75,0,1,0,1,1
4,1,0,0,0,2,1,1,70.70,151.65,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,0,1,24,1,1,84.80,1990.50,0,1,0,1,1
7039,1,0,0,1,72,1,1,103.20,7362.90,0,0,1,1,0
7040,1,0,0,1,11,0,1,29.60,346.45,0,1,0,0,0
7041,0,1,0,0,4,1,1,74.40,306.60,1,0,0,0,0
7042,0,0,0,0,66,1,1,105.65,6844.50,0,1,0,1,1

In [1285]:
df

,PaymentMethod,MultipleLines,InternetService,StreamingTV,StreamingMovies
0,Electronic check,No phone service,DSL,No,No
1,Mailed check,No,DSL,No,No
2,Mailed check,No,DSL,No,No
3,Bank transfer (automatic),No phone service,DSL,No,No
4,Electronic check,No,Fiber optic,No,No
...,...,...,...,...,...
7038,Mailed check,Yes,DSL,Yes,Yes
7039,Credit card (automatic),Yes,Fiber optic,Yes,Yes
7040,Electronic check,No phone service,DSL,No,No
7041,Mailed check,Yes,Fiber optic,No,No
7042,Bank transfer (automatic),No,Fiber optic,Yes,Yes

In [1286]:
df['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [1287]:
df_car=df.rename(columns={'MultipleLines':'Multi','InternetService':'inter'})
df_car

,PaymentMethod,Multi,inter,StreamingTV,StreamingMovies
0,Electronic check,No phone service,DSL,No,No
1,Mailed check,No,DSL,No,No
2,Mailed check,No,DSL,No,No
3,Bank transfer (automatic),No phone service,DSL,No,No
4,Electronic check,No,Fiber optic,No,No
...,...,...,...,...,...
7038,Mailed check,Yes,DSL,Yes,Yes
7039,Credit card (automatic),Yes,Fiber optic,Yes,Yes
7040,Electronic check,No phone service,DSL,No,No
7041,Mailed check,Yes,Fiber optic,No,No
7042,Bank transfer (automatic),No,Fiber optic,Yes,Yes

In [1288]:
dummi=pd.get_dummies(df_car,dtype=int,drop_first=True)
dummi

,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Multi_No phone service,Multi_Yes,inter_Fiber optic,inter_No,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes
0,0,1,0,1,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0
4,0,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,0,1,0,0,0,1,0,1
7039,1,0,0,0,1,1,0,0,1,0,1
7040,0,1,0,1,0,0,0,0,0,0,0
7041,0,0,1,0,1,1,0,0,0,0,0
7042,0,0,0,0,0,1,0,0,1,0,1

In [1289]:
df_original=pd.concat([dummi,df_car],axis=1)
df_original

,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Multi_No phone service,Multi_Yes,inter_Fiber optic,inter_No,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,PaymentMethod,Multi,inter,StreamingTV,StreamingMovies
0,0,1,0,1,0,0,0,0,0,0,0,Electronic check,No phone service,DSL,No,No
1,0,0,1,0,0,0,0,0,0,0,0,Mailed check,No,DSL,No,No
2,0,0,1,0,0,0,0,0,0,0,0,Mailed check,No,DSL,No,No
3,0,0,0,1,0,0,0,0,0,0,0,Bank transfer (automatic),No phone service,DSL,No,No
4,0,1,0,0,0,1,0,0,0,0,0,Electronic check,No,Fiber optic,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,0,1,0,0,0,1,0,1,Mailed check,Yes,DSL,Yes,Yes
7039,1,0,0,0,1,1,0,0,1,0,1,Credit card (automatic),Yes,Fiber optic,Yes,Yes
7040,0,1,0,1,0,0,0,0,0,0,0,Electronic check,No phone service,DSL,No,No
7041,0,0,1,0,1,1,0,0,0,0,0,Mailed check,Yes,Fiber optic,No,No
7042,0,0,0,0,0,1,0,0,1,0,1,Bank transfer (automatic),No,Fiber optic,Yes,Yes

In [1290]:
df1

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport
0,1,0,0,0,1,0,1,29.85,29.85,0,0,1,0,0
1,0,0,0,0,34,1,0,56.95,1889.50,0,1,0,1,0
2,0,0,0,0,2,1,1,53.85,108.15,1,1,1,0,0
3,0,0,0,0,45,0,0,42.30,1840.75,0,1,0,1,1
4,1,0,0,0,2,1,1,70.70,151.65,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,0,1,24,1,1,84.80,1990.50,0,1,0,1,1
7039,1,0,0,1,72,1,1,103.20,7362.90,0,0,1,1,0
7040,1,0,0,1,11,0,1,29.60,346.45,0,1,0,0,0
7041,0,1,0,0,4,1,1,74.40,306.60,1,0,0,0,0
7042,0,0,0,0,66,1,1,105.65,6844.50,0,1,0,1,1

In [1291]:
x=df1[['MonthlyCharges','TotalCharges']]
x

      MonthlyCharges  TotalCharges
0              29.85         29.85
1              56.95       1889.50
2              53.85        108.15
3              42.30       1840.75
4              70.70        151.65
...              ...           ...
7038           84.80       1990.50
7039          103.20       7362.90
7040           29.60        346.45
7041           74.40        306.60
7042          105.65       6844.50

[7043 rows x 2 columns]

In [1292]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (1.7.0)
Requirement already satisfied: numpy>=1.22.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.0.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1293]:
from sklearn.preprocessing import StandardScaler

In [1294]:

scaler=StandardScaler()
x_scale=scaler.fit_transform(x)

In [1295]:
pd.DataFrame(x_scale)

             0         1
0    -1.160323 -0.994194
1    -0.259629 -0.173740
2    -0.362660 -0.959649
3    -0.746535 -0.195248
4     0.197365 -0.940457
...        ...       ...
7038  0.665992 -0.129180
7039  1.277533  2.241056
7040 -1.168632 -0.854514
7041  0.320338 -0.872095
7042  1.358961  2.012344

[7043 rows x 2 columns]

In [1296]:
df_x_scaled=pd.DataFrame(x_scale,columns=['	MonthlyCharges','TotalCharges'])
df_x_scaled

      \tMonthlyCharges  TotalCharges
0            -1.160323     -0.994194
1            -0.259629     -0.173740
2            -0.362660     -0.959649
3            -0.746535     -0.195248
4             0.197365     -0.940457
...                ...           ...
7038          0.665992     -0.129180
7039          1.277533      2.241056
7040         -1.168632     -0.854514
7041          0.320338     -0.872095
7042          1.358961      2.012344

[7043 rows x 2 columns]

In [1299]:
df1

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport
0,1,0,0,0,1,0,1,29.85,29.85,0,0,1,0,0
1,0,0,0,0,34,1,0,56.95,1889.50,0,1,0,1,0
2,0,0,0,0,2,1,1,53.85,108.15,1,1,1,0,0
3,0,0,0,0,45,0,0,42.30,1840.75,0,1,0,1,1
4,1,0,0,0,2,1,1,70.70,151.65,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,0,1,24,1,1,84.80,1990.50,0,1,0,1,1
7039,1,0,0,1,72,1,1,103.20,7362.90,0,0,1,1,0
7040,1,0,0,1,11,0,1,29.60,346.45,0,1,0,0,0
7041,0,1,0,0,4,1,1,74.40,306.60,1,0,0,0,0
7042,0,0,0,0,66,1,1,105.65,6844.50,0,1,0,1,1

In [1301]:
x=df1[['MonthlyCharges','TotalCharges']]
x

      MonthlyCharges  TotalCharges
0              29.85         29.85
1              56.95       1889.50
2              53.85        108.15
3              42.30       1840.75
4              70.70        151.65
...              ...           ...
7038           84.80       1990.50
7039          103.20       7362.90
7040           29.60        346.45
7041           74.40        306.60
7042          105.65       6844.50

[7043 rows x 2 columns]

In [1298]:
x.drop(['MonthlyCharges','TotalCharges'],axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[7043 rows x 0 columns]