Pandas Series

A series is one diamensional labeled array capable of holding any data type.
The axis label are collectivelycalled the index.

Creating Series

There are multiple way of pandas series.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels=['a','b','c']
my_list=[10,20,30]
my_arr=np.array([10,20,30])
dic={'a':10,'b':20,'c':30}

In [4]:
pd.Series(my_list)
# 0,1,2 is index  or labels point
# 10,20,30 is Data point

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(my_arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(my_arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(dic)

a    10
b    20
c    30
dtype: int64

Data Frame

When you combine a multiple series together is called a data frame.

In [9]:
import numpy as np
import pandas as pd

Create a DataFrame

In [10]:
data ={
    'Name':['john','Anna','peter','Linda'],
    'Age' :[28,34,29,42],
    'City':['Newyork','Paris',"London",'Berlin'],
    'Salary':[65000,70000,62000,85000]

}
df=pd.DataFrame(data)

In [11]:
df

    Name  Age     City  Salary
0   john   28  Newyork   65000
1   Anna   34    Paris   70000
2  peter   29   London   62000
3  Linda   42   Berlin   85000

In [12]:
data_list=[
    ['jonn',28,'Newyork',65000],
    ['Anna',34,'paris',70000],
    ['peter',29,'LOndon',62000],
    ['Linda',42,'Berlin',85000]
]
df2=pd.DataFrame(data_list)
column=['Name',"Age",'City','Salary']
df2=pd.DataFrame(data_list,columns=column)

In [13]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

Slelection and Indexing of columns

In [14]:
df2[['Name',"City"]]

    Name     City
0   jonn  Newyork
1   Anna    paris
2  peter   LOndon
3  Linda   Berlin

Creating  a new  Columns

In [15]:
df2['Designation']=['Doctor','Eng','Scientist','Eng']

In [16]:
df2

    Name  Age     City  Salary Designation
0   jonn   28  Newyork   65000      Doctor
1   Anna   34    paris   70000         Eng
2  peter   29   LOndon   62000   Scientist
3  Linda   42   Berlin   85000         Eng

Removing  a Columns

In [17]:
df2.drop('Designation',axis=1,inplace=True)

In [18]:
df2.drop(['Age','Salary'],axis=1)

    Name     City
0   jonn  Newyork
1   Anna    paris
2  peter   LOndon
3  Linda   Berlin

In [19]:
df2.drop(2,axis=0)

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
3  Linda   42   Berlin   85000

In [20]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [21]:
#  loc mean a location
df2.loc[0]

Name         jonn
Age            28
City      Newyork
Salary      65000
Name: 0, dtype: object

In [22]:
df2.loc[[0,1,3]]

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
3  Linda   42   Berlin   85000

In [23]:
# iloc mean a index locaton
df2.iloc[0]

Name         jonn
Age            28
City      Newyork
Salary      65000
Name: 0, dtype: object

Selectiing Subset of row and column

In [24]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [25]:
df.loc[[0,1]][['City','Salary']]

      City  Salary
0  Newyork   65000
1    Paris   70000

In [26]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  peter   29
3  Linda   42

In [27]:
df.loc[[1,3]][['Age','Salary']]

   Age  Salary
1   34   70000
3   42   85000

Conditional Selection

In [28]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [29]:
df2[df2['Age']>39]

    Name  Age    City  Salary
3  Linda   42  Berlin   85000

In [30]:
# I only want to see those people  whose age is above 30
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   paris   70000
3  Linda   42  Berlin   85000

In [31]:
# I only want to see those people  whose age is above 30  and their city ust be paris
df2[(df2['Age'] >30) & (df2['City']=='paris')]

   Name  Age   City  Salary
1  Anna   34  paris   70000

In [32]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [33]:
df2[(df2['Age'] > 30) & (df2['Salary'] >=70000)]

    Name  Age    City  Salary
1   Anna   34   paris   70000
3  Linda   42  Berlin   85000

3.Missing Data

In [34]:
import numpy as np
import pandas as pd

In [35]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}

In [36]:
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [37]:
# isna sa null value check karta ha 
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [38]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [39]:
# asiya koi kolumn ha ki jisma koi missing value ha 
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [40]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Remove Missing Value

In [41]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [42]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [43]:
# dropna means a hole table check a null value jis ma bhi ni=ull value hongi vahi delete ho gayanga

df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [44]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [45]:
#  thresh mean a 4 non null value hona chiya
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

Filling the Missing value

In [46]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [47]:
df.fillna('sohel')

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  sohel
2  sohel  3    3.0  sohel
3    4.0  4  sohel  sohel
4    5.0  5  sohel    5.0

In [48]:

df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [49]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [50]:
s={'A':0,'B':100,'C':300,'D':500}
df.fillna(value=s)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  500.0
2  0.0  3    3.0  500.0
3  4.0  4  300.0  500.0
4  5.0  5  300.0    5.0

In [51]:
values={'A':0,'B':100,'C':300,"D":400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [52]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [53]:
df.fillna(df.median())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [54]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [55]:
df.fillna(1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  1.0  3  3.0  1.0
3  4.0  4  1.0  1.0
4  5.0  5  1.0  5.0

4. Merging Joining And Concatination

In [56]:
import numpy as np
import pandas as pd

In [57]:
employees=pd.DataFrame({
    'Employee_id':[1,2,3,4,5],
    'Name':['John','Anna','Peter','Linda','Bob'],
    'Depertment':['HR','IT','Finance','IT','HR']
})

Salaries=pd.DataFrame({
    'Employee_id':[1,2,3,6,7],
    'Salary':[6000,8000,65000,70000,90000],
    'Bonus':[5000,10000,7000,80000,12000],
})

In [58]:
employees

   Employee_id   Name Depertment
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [59]:
Salaries

   Employee_id  Salary  Bonus
0            1    6000   5000
1            2    8000  10000
2            3   65000   7000
3            6   70000  80000
4            7   90000  12000

In [60]:
pd.merge(employees,Salaries,on='Employee_id',how='inner')

   Employee_id   Name Depertment  Salary  Bonus
0            1   John         HR    6000   5000
1            2   Anna         IT    8000  10000
2            3  Peter    Finance   65000   7000

In [61]:
pd.merge(employees,Salaries,on='Employee_id',how='outer')

   Employee_id   Name Depertment   Salary    Bonus
0            1   John         HR   6000.0   5000.0
1            2   Anna         IT   8000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0  80000.0
6            7    NaN        NaN  90000.0  12000.0

In [62]:
pd.merge(employees,Salaries,how='outer')

   Employee_id   Name Depertment   Salary    Bonus
0            1   John         HR   6000.0   5000.0
1            2   Anna         IT   8000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0  80000.0
6            7    NaN        NaN  90000.0  12000.0

In [63]:
pd.merge(employees,Salaries,on='Employee_id',how='outer')

   Employee_id   Name Depertment   Salary    Bonus
0            1   John         HR   6000.0   5000.0
1            2   Anna         IT   8000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0  80000.0
6            7    NaN        NaN  90000.0  12000.0

In [64]:
pd.merge(employees,Salaries,how='left')

   Employee_id   Name Depertment   Salary    Bonus
0            1   John         HR   6000.0   5000.0
1            2   Anna         IT   8000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [65]:
pd.merge(employees,Salaries,how='right')

   Employee_id   Name Depertment  Salary  Bonus
0            1   John         HR    6000   5000
1            2   Anna         IT    8000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000  80000
4            7    NaN        NaN   90000  12000

In [66]:
# salary ka data  pa chalta ha 
pd.merge(employees,Salaries,on='Employee_id',how='outer')

   Employee_id   Name Depertment   Salary    Bonus
0            1   John         HR   6000.0   5000.0
1            2   Anna         IT   8000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0  80000.0
6            7    NaN        NaN  90000.0  12000.0

Concatination of 2 dataframe

In [67]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2'],
})

df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5'],
})

In [68]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [69]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [70]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [71]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [72]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [73]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [74]:
pd.concat([df1,df2],axis=0)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

Joining to data Frame

In [75]:
# firsr data frame
df1=pd.DataFrame({
    'name':['Alice','Bob','Charlie'],
    
},index=[1,2,3])

# sec data frame
df2=pd.DataFrame({
    'Score':[85,90,75]
},index=[2,3,4])

In [76]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [77]:
df2

   Score
2     85
3     90
4     75

In [78]:
df1.join(df2,how='outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [79]:
df1.join(df2,how='inner')

      name  Score
2      Bob     85
3  Charlie     90

In [80]:
df1.join(df2)

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [81]:
df1.join(df2,how='outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [82]:
df2.join(df1)

   Score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [83]:
df2.join(df1,how='outer')

   Score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN

Group by and aggregression

In [84]:
import numpy as np
import pandas as pd

GroupBy

In [85]:
data = {
    'category':['A','B','A','B','A','B','A','B'],
    'Store':['s1','s1','s2','s2','s1','s2','s2','s1'],
    'sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Data':pd.date_range('2023-01-01',periods=8)

}
df=pd.DataFrame(data)
df

  category Store  sales  Quantity       Data
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

Que 1 . Group by categories and calculate the sum of sales

In [86]:
cat=df.groupby('category')['sales'].sum()
cat

category
A    570
B    930
Name: sales, dtype: int64

Que 2. Group by store and calculate the sum of sales

In [87]:
df

  category Store  sales  Quantity       Data
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

In [88]:

df.groupby('Store')['sales'].sum()

Store
s1    720
s2    780
Name: sales, dtype: int64

Que 3 .Group by mul column
category and storage

In [89]:
df.groupby(['category','Store'])['sales'].sum()

category  Store
A         s1       220
          s2       350
B         s1       500
          s2       430
Name: sales, dtype: int64

Aggregration

In [90]:
df

  category Store  sales  Quantity       Data
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

In [91]:
df['sales'].mode()

0    200
Name: sales, dtype: int64

In [92]:
df['sales'].median()

np.float64(190.0)

In [93]:
df['sales'].std()

np.float64(66.06274074155351)

In [94]:
df['sales'].min()

np.int64(100)

In [95]:
df['sales'].max

<bound method Series.max of 0    100
1    200
2    150
3    250
4    120
5    180
6    200
7    300
Name: sales, dtype: int64>

In [96]:
df

  category Store  sales  Quantity       Data
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

In [97]:
cat=df.groupby(['category','Store'])['sales'].sum()
cat

category  Store
A         s1       220
          s2       350
B         s1       500
          s2       430
Name: sales, dtype: int64

In [98]:
df.groupby(['category','Data'])['sales'].sum()

category  Data
A         2023-01-01    100
          2023-01-03    150
          2023-01-05    120
          2023-01-07    200
B         2023-01-02    200
          2023-01-04    250
          2023-01-06    180
          2023-01-08    300
Name: sales, dtype: int64

In [99]:
df['sales'].agg(['sum','min','max','count','std'])

sum      1500.000000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
Name: sales, dtype: float64

Pivot Table

In [100]:
import numpy as np
import pandas as pd

Pivot Table

In [101]:


# Creating the data
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'Nort', 'South', 'East', 'West', 'Nort', 'South', 'East', 'West',
               'Nort', 'South', 'East', 'West', 'Nort', 'South', 'East', 'West', 'Nort', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'units': np.random.randint(10, 100, 20),
    'Rep': ['john', 'Merry', 'Bob', 'Alice', 'john', 'Merry', 'Bob', 'Alice', 'john', 'Merry',
            'Bob', 'Alice', 'john', 'Merry', 'Bob', 'Alice', 'john', 'Merry', 'Bob', 'Alice']
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Adding Month and Quarter columns
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

# Display the result
df

         Date product Region  Sales  units    Rep    Month Quarter
0  2023-01-01       A   East    172     39   john  January      Q1
1  2023-01-02       B   West    829     35  Merry  January      Q1
2  2023-01-03       C   Nort    800     33    Bob  January      Q1
3  2023-01-04       D  South    276     93  Alice  January      Q1
4  2023-01-05       A   East    334     25   john  January      Q1
5  2023-01-06       B   West    583     39  Merry  January      Q1
6  2023-01-07       C   Nort    748     28    Bob  January      Q1
7  2023-01-08       D  South    852     86  Alice  January      Q1
8  2023-01-09       A   East    706     39   john  January      Q1
9  2023-01-10       B   West    983     14  Merry  January      Q1
10 2023-01-11       C   Nort    221     96    Bob  January      Q1
11 2023-01-12       D  South    696     48  Alice  January      Q1
12 2023-01-13       A   East    592     59   john  January      Q1
13 2023-01-14       B   West    562     31  Merry  January      Q1
14 2023-01-15       C   Nort    801     78    Bob  January      Q1
15 2023-01-16       D  South    807     12  Alice  January      Q1
16 2023-01-17       A   East    777     23   john  January      Q1
17 2023-01-18       B   West    127     59  Merry  January      Q1
18 2023-01-19       C   Nort    438     97    Bob  January      Q1
19 2023-01-20       D  South    974     15  Alice  January      Q1

In [102]:
# aggregration are use in pivot table
pd.pivot_table(df,values='Sales',index='Region',columns='product',aggfunc='median')

product      A      B      C      D
Region
East     592.0    NaN    NaN    NaN
Nort       NaN    NaN  748.0    NaN
South      NaN    NaN    NaN  807.0
West       NaN  583.0    NaN    NaN

In [103]:
pd.pivot_table(df,values=['Sales','units'],index='Region',columns='product')

         Sales                      units
product      A      B      C      D     A     B     C     D
Region
East     516.2    NaN    NaN    NaN  37.0   NaN   NaN   NaN
Nort       NaN    NaN  601.6    NaN   NaN   NaN  66.4   NaN
South      NaN    NaN    NaN  721.0   NaN   NaN   NaN  50.8
West       NaN  616.8    NaN    NaN   NaN  35.6   NaN   NaN

Cross Tabs

In [104]:
# cross tab are use at a counting purpose
pd.crosstab(df['Region'],df['product'])

product  A  B  C  D
Region
East     5  0  0  0
Nort     0  0  5  0
South    0  0  0  5
West     0  5  0  0

Operation

In [105]:
import numpy as np
import pandas as pd

In [106]:
df1= pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})

In [107]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [108]:
# shape is a attribute is not a fun
df1.shape

(5, 3)

In [109]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [110]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [111]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [112]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

DataFrame Applying Function

In [113]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [114]:
def square(x):
    return x**2

In [115]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [116]:
df1['D']=df1['B'].apply(square)

In [117]:
# or
df1['E'] =df1['B'].apply(lambda x:x**3)

In [118]:
df1

   A   B    C     D       E
0  1  10  100   100    1000
1  2  20  200   400    8000
2  3  30  300   900   27000
3  4  40  400  1600   64000
4  5  50  500  2500  125000

ANEMA PROJECT

Loading  the data

In [119]:
import numpy  as np
import pandas as pd

In [120]:
df=pd.read_csv(r'Animation.csv')

In [121]:
df

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
0,1,Cowboy Bebop,Original,Bandai Visual,Action,Sunrise,26.0,False,26,39,795733,43460,405664,8.81
1,5,Cowboy Bebop: Tengoku no Tobira,Original,Sunrise,Action,Bones,1.0,False,164,449,197791,776,120243,8.41
2,6,Trigun,Manga,Victor Entertainment,Action,Madhouse,26.0,False,255,146,408548,10432,212537,8.30
3,7,Witch Hunter Robin,Original,Bandai Visual,Action,Sunrise,26.0,False,2371,1171,79397,537,32837,7.33
4,8,Bouken Ou Beet,Manga,TV Tokyo,Adventure,Toei Animation,52.0,False,3544,3704,11708,14,4894,7.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13626,39189,Te Ke Dong Ji Pian,Unknown,NaN,Action,NaN,54.0,False,13301,15461,7,0,0,NaN
13627,39190,Wang Zhe Wai Chuan,Unknown,NaN,Comedy,NaN,12.0,False,13570,15472,7,0,0,NaN
13628,39191,Wan Jie Shen Zhu,Unknown,NaN,Fantasy,NaN,60.0,False,13568,15470,7,0,0,NaN
13629,39192,Xia Gu Zhong An Zu,Unknown,NaN,Fantasy,NaN,12.0,False,13635,15473,7,0,0,NaN
13630,39197,Karrimor Mountain Club,Original,NaN,Adventure,NaN,4.0,False,11624,15424,10,0,0,NaN

In [122]:
# .head mean a starting ka 5 data 
df1=df.head()
df1

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
0,1,Cowboy Bebop,Original,Bandai Visual,Action,Sunrise,26.0,False,26,39,795733,43460,405664,8.81
1,5,Cowboy Bebop: Tengoku no Tobira,Original,Sunrise,Action,Bones,1.0,False,164,449,197791,776,120243,8.41
2,6,Trigun,Manga,Victor Entertainment,Action,Madhouse,26.0,False,255,146,408548,10432,212537,8.30
3,7,Witch Hunter Robin,Original,Bandai Visual,Action,Sunrise,26.0,False,2371,1171,79397,537,32837,7.33
4,8,Bouken Ou Beet,Manga,TV Tokyo,Adventure,Toei Animation,52.0,False,3544,3704,11708,14,4894,7.03

In [123]:
df.loc[2]['name']

'Trigun'

In [124]:
df1['producers'].astype(str)

0           Bandai Visual
1                 Sunrise
2    Victor Entertainment
3           Bandai Visual
4                TV Tokyo
Name: producers, dtype: object

In [125]:
df1

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
0,1,Cowboy Bebop,Original,Bandai Visual,Action,Sunrise,26.0,False,26,39,795733,43460,405664,8.81
1,5,Cowboy Bebop: Tengoku no Tobira,Original,Sunrise,Action,Bones,1.0,False,164,449,197791,776,120243,8.41
2,6,Trigun,Manga,Victor Entertainment,Action,Madhouse,26.0,False,255,146,408548,10432,212537,8.30
3,7,Witch Hunter Robin,Original,Bandai Visual,Action,Sunrise,26.0,False,2371,1171,79397,537,32837,7.33
4,8,Bouken Ou Beet,Manga,TV Tokyo,Adventure,Toei Animation,52.0,False,3544,3704,11708,14,4894,7.03

In [126]:
df1['genre'].unique()
df1['genre'].map({'Action':0,'Adventure':1})

0    0
1    0
2    0
3    0
4    1
Name: genre, dtype: int64

Highest score to extract

In [127]:
df1[df1['episodes'] == df['episodes'].min()]

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
1,5,Cowboy Bebop: Tengoku no Tobira,Original,Sunrise,Action,Bones,1.0,False,164,449,197791,776,120243,8.41

Give me top5 to extract

In [128]:
df['episodes'].head()

0    26.0
1     1.0
2    26.0
3    26.0
4    52.0
Name: episodes, dtype: float64

In [129]:
df[df['episodes'] == df['episodes'].max()]

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
4996,9947,Lan Mao,Original,Beijing Sunchime Happy Culture Company,Adventure,NaN,3057.0,False,11813,10422,448,0,11,5.64

In [130]:
# df['episodes'].value_counts
# or 

df1['episodes'].unique()

array([26.,  1., 52.])

In [131]:
df1['episodes'].sort_values()

1     1.0
0    26.0
2    26.0
3    26.0
4    52.0
Name: episodes, dtype: float64

In [132]:
df

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
0,1,Cowboy Bebop,Original,Bandai Visual,Action,Sunrise,26.0,False,26,39,795733,43460,405664,8.81
1,5,Cowboy Bebop: Tengoku no Tobira,Original,Sunrise,Action,Bones,1.0,False,164,449,197791,776,120243,8.41
2,6,Trigun,Manga,Victor Entertainment,Action,Madhouse,26.0,False,255,146,408548,10432,212537,8.30
3,7,Witch Hunter Robin,Original,Bandai Visual,Action,Sunrise,26.0,False,2371,1171,79397,537,32837,7.33
4,8,Bouken Ou Beet,Manga,TV Tokyo,Adventure,Toei Animation,52.0,False,3544,3704,11708,14,4894,7.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13626,39189,Te Ke Dong Ji Pian,Unknown,NaN,Action,NaN,54.0,False,13301,15461,7,0,0,NaN
13627,39190,Wang Zhe Wai Chuan,Unknown,NaN,Comedy,NaN,12.0,False,13570,15472,7,0,0,NaN
13628,39191,Wan Jie Shen Zhu,Unknown,NaN,Fantasy,NaN,60.0,False,13568,15470,7,0,0,NaN
13629,39192,Xia Gu Zhong An Zu,Unknown,NaN,Fantasy,NaN,12.0,False,13635,15473,7,0,0,NaN
13630,39197,Karrimor Mountain Club,Original,NaN,Adventure,NaN,4.0,False,11624,15424,10,0,0,NaN

In [133]:
df['airing'].unique()
df['airing']=df['airing'].map({'False':0,'True':1})
df['airing']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
13626   NaN
13627   NaN
13628   NaN
13629   NaN
13630   NaN
Name: airing, Length: 13631, dtype: float64