In [81]:
import numpy as np
import pandas as pd

In [82]:
label=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [83]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [84]:
pd.Series(my_list,index=label)

a    10
b    20
c    30
dtype: int64

In [85]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [86]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

Create a Dataframe

In [87]:
data ={
    'Name':['john','Anna','peter','Linda'],
    'Age' :[28,34,29,42],
    'City':['Newyork','Paris',"London",'Berlin'],
    'Salary':[65000,70000,62000,85000]

}
df=pd.DataFrame(data)
df

    Name  Age     City  Salary
0   john   28  Newyork   65000
1   Anna   34    Paris   70000
2  peter   29   London   62000
3  Linda   42   Berlin   85000

In [88]:
data_list=[
    ['jonn',28,'Newyork',65000],
    ['Anna',34,'paris',70000],
    ['peter',29,'LOndon',62000],
    ['Linda',42,'Berlin',85000]
]
df2=pd.DataFrame(data_list)
columns=['Name','Age',"City",'Salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [89]:
# selection and indexingg of columns
df2[['Name','City']]

    Name     City
0   jonn  Newyork
1   Anna    paris
2  peter   LOndon
3  Linda   Berlin

In [90]:
# Creating a new columns
df2["Designation"]=['Doctor',"Eng","Doctor","Eng"]
df2

    Name  Age     City  Salary Designation
0   jonn   28  Newyork   65000      Doctor
1   Anna   34    paris   70000         Eng
2  peter   29   LOndon   62000      Doctor
3  Linda   42   Berlin   85000         Eng

In [91]:
# Descination 
df2.drop('Designation',axis=1,inplace=True)

In [92]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   paris   70000
2  peter   29  LOndon   62000
3  Linda   42  Berlin   85000

In [93]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

Selecting  Rows

In [94]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [95]:
df.loc[[0,3]]

    Name  Age     City  Salary
0   john   28  Newyork   65000
3  Linda   42   Berlin   85000

In [96]:
df.iloc[2]

Name       peter
Age           29
City      London
Salary     62000
Name: 2, dtype: object

In [97]:
df.loc[[0,1]][['City','Salary']]

      City  Salary
0  Newyork   65000
1    Paris   70000

In [98]:
df.loc[[0,1]][['Name','Age']]

   Name  Age
0  john   28
1  Anna   34

Conditional Statement

In [99]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [100]:
# I only want to see those people age is above 30
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   paris   70000
3  Linda   42  Berlin   85000

In [101]:
df2[(df2['Age'] >30) & (df2['City']=='paris')]

   Name  Age   City  Salary
1  Anna   34  paris   70000

In [102]:
df2[(df2['Age']>30) & (df2['Salary']>65000)]

    Name  Age    City  Salary
1   Anna   34   paris   70000
3  Linda   42  Berlin   85000

In [103]:
# Finding Missing data
data={
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [104]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [105]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [106]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [108]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [111]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [113]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Filling the missing data

In [ ]:
# selection hota ha column wise fill hota  ha  vo bhi column vise

In [115]:
df.fillna(value=0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [116]:
Values={'A':50,'B':100,"C":300,'D':400}
df.fillna(value=Values)

      A  B      C      D
0   1.0  1    1.0    1.0
1   2.0  2    2.0  400.0
2  50.0  3    3.0  400.0
3   4.0  4  300.0  400.0
4   5.0  5  300.0    5.0

In [117]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [118]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

Merging Joining and concatination

In [119]:
df2

    Name  Age     City  Salary
0   jonn   28  Newyork   65000
1   Anna   34    paris   70000
2  peter   29   LOndon   62000
3  Linda   42   Berlin   85000

In [124]:
employees=pd.DataFrame({
    'Employee_id':[1,2,3,4,5],
    'Name':['John','Anna','Peter','Linda','Bob'],
    'Depertment':['HR','IT','Finance','IT','HR']
})

Salaries=pd.DataFrame({
    'Employee_id':[1,2,3,6,7],
    'Salary':[6000,8000,65000,70000,90000],
    'Bonus':[5000,10000,7000,80000,12000],
})

In [126]:
employees

   Employee_id   Name Depertment
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [129]:
Salaries

   Employee_id  Salary  Bonus
0            1    6000   5000
1            2    8000  10000
2            3   65000   7000
3            6   70000  80000
4            7   90000  12000

In [ ]:
pd.merge(employees,Salaries,on='Employee_id',how='inner')

   Employee_id   Name Depertment  Salary  Bonus
0            1   John         HR    6000   5000
1            2   Anna         IT    8000  10000
2            3  Peter    Finance   65000   7000

In [136]:
pd.merge(employees,Salaries,on='Employee_id',how='outer')

   Employee_id   Name Depertment   Salary    Bonus
0            1   John         HR   6000.0   5000.0
1            2   Anna         IT   8000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0  80000.0
6            7    NaN        NaN  90000.0  12000.0

In [139]:
pd.merge(employees,Salaries,on='Employee_id',how='left')

   Employee_id   Name Depertment   Salary    Bonus
0            1   John         HR   6000.0   5000.0
1            2   Anna         IT   8000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [140]:
pd.merge(employees,Salaries,on='Employee_id',how='right')

   Employee_id   Name Depertment  Salary  Bonus
0            1   John         HR    6000   5000
1            2   Anna         IT    8000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000  80000
4            7    NaN        NaN   90000  12000

Concantination of 2 data frame

In [142]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2'],
})

df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5'],
})
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [143]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [148]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining 2 data frame

In [149]:
df1=pd.DataFrame({
    'name':['Alice','Bob','Charlie'],
    
},index=[1,2,3])

# sec data frame
df2=pd.DataFrame({
    'Score':[85,90,75]
},index=[2,3,4])

In [150]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [151]:
df2

   Score
2     85
3     90
4     75

In [156]:
df1.join(df2,how='outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

GroupBY

In [1]:
import numpy as np
import pandas as pd

In [9]:
data = {
    'category':['A','B','A','B','A','B','A','B'],
    'Store':['s1','s1','s2','s2','s1','s2','s2','s1'],
    'sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Data':pd.date_range('2023-02-01',periods=8)

}
df=pd.DataFrame(data)
df

  category Store  sales  Quantity       Data
0        A    s1    100        10 2023-02-01
1        B    s1    200        15 2023-02-02
2        A    s2    150        12 2023-02-03
3        B    s2    250        18 2023-02-04
4        A    s1    120         8 2023-02-05
5        B    s2    180        20 2023-02-06
6        A    s2    200        15 2023-02-07
7        B    s1    300        25 2023-02-08

In [14]:
# Group by the category the sum of sales
cat=df.groupby('category')['sales'].sum()
cat

category
A    570
B    930
Name: sales, dtype: int64

In [ ]:
#  store and calcularte  sum of sales
ca=df.groupby('Store')['sales'].sum()
ca

Store
s1    720
s2    780
Name: sales, dtype: int64

In [19]:
# Gropu by multiple columns
cat=df.groupby(['category','Store'])['sales'].sum()
cat

category  Store
A         s1       220
          s2       350
B         s1       500
          s2       430
Name: sales, dtype: int64

Aggregration

In [24]:
df['sales'].mean()

187.5

In [25]:
df['sales'].mode()

0    200
Name: sales, dtype: int64

In [27]:
df['sales'].median()

190.0

In [26]:
df['sales'].max()

300

In [30]:
df['sales'].agg(['sum','mean','median','min','max'])

sum       1500.0
mean       187.5
median     190.0
min        100.0
max        300.0
Name: sales, dtype: float64

Pivottable

In [31]:
import numpy as np
import pandas as pd

In [35]:
# Creating the data
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'Nort', 'South', 'East', 'West', 'Nort', 'South', 'East', 'West',
               'Nort', 'South', 'East', 'West', 'Nort', 'South', 'East', 'West', 'Nort', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'units': np.random.randint(10, 100, 20),
    'Rep': ['john', 'Merry', 'Bob', 'Alice', 'john', 'Merry', 'Bob', 'Alice', 'john', 'Merry',
            'Bob', 'Alice', 'john', 'Merry', 'Bob', 'Alice', 'john', 'Merry', 'Bob', 'Alice']
}
df=pd.DataFrame(data)

df['Month']=df['Date'].dt.month_name()
df['Quantity']='Q'+df['Date'].dt.quarter.astype(str)

df

         Date product Region  Sales  units    Rep    Month Quantity
0  2023-01-01       A   East    712     16   john  January       Q1
1  2023-01-02       B   West    373     34  Merry  January       Q1
2  2023-01-03       C   Nort    568     13    Bob  January       Q1
3  2023-01-04       D  South    637     38  Alice  January       Q1
4  2023-01-05       A   East    683     96   john  January       Q1
5  2023-01-06       B   West    995     96  Merry  January       Q1
6  2023-01-07       C   Nort    384     52    Bob  January       Q1
7  2023-01-08       D  South    292     99  Alice  January       Q1
8  2023-01-09       A   East    968     77   john  January       Q1
9  2023-01-10       B   West    464     42  Merry  January       Q1
10 2023-01-11       C   Nort    817     31    Bob  January       Q1
11 2023-01-12       D  South    876     98  Alice  January       Q1
12 2023-01-13       A   East    149     38   john  January       Q1
13 2023-01-14       B   West    235     28  Merry  January       Q1
14 2023-01-15       C   Nort    649     15    Bob  January       Q1
15 2023-01-16       D  South    830     35  Alice  January       Q1
16 2023-01-17       A   East    269     44   john  January       Q1
17 2023-01-18       B   West    910     49  Merry  January       Q1
18 2023-01-19       C   Nort    639     54    Bob  January       Q1
19 2023-01-20       D  South    875     90  Alice  January       Q1

In [37]:
pd.pivot_table(df,values='Sales',index='Region',columns='product',aggfunc='median')

product      A      B      C      D
Region
East     683.0    NaN    NaN    NaN
Nort       NaN    NaN  639.0    NaN
South      NaN    NaN    NaN  830.0
West       NaN  464.0    NaN    NaN

In [42]:
pivot2=pd.pivot_table(df,values=['Sales','units'],index='Region',columns='product',aggfunc='median')
pivot2

         Sales                      units
product      A      B      C      D     A     B     C     D
Region
East     683.0    NaN    NaN    NaN  44.0   NaN   NaN   NaN
Nort       NaN    NaN  639.0    NaN   NaN   NaN  31.0   NaN
South      NaN    NaN    NaN  830.0   NaN   NaN   NaN  90.0
West       NaN  464.0    NaN    NaN   NaN  42.0   NaN   NaN

Cross Table

In [43]:
pd.crosstab(df['Region'],df['product'])

product  A  B  C  D
Region
East     5  0  0  0
Nort     0  0  5  0
South    0  0  0  5
West     0  5  0  0

Data Frame Basic Operation

In [18]:
import numpy as np
import pandas as pd

In [19]:
df1= pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

Data Frame Apply Function

In [20]:
df1.shape

(5, 3)

In [22]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [24]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [25]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

Data Frame Applying Function

In [26]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [29]:
def square(x):
    return x**2
df1['D']=df1['B'].apply(lambda x:x**2)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [30]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

Project of feature extracton

In [31]:
import numpy as np
import pandas as pd

In [34]:
df=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\python\Pandad\Animation.csv")
df

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
0,1,Cowboy Bebop,Original,Bandai Visual,Action,Sunrise,26.0,False,26,39,795733,43460,405664,8.81
1,5,Cowboy Bebop: Tengoku no Tobira,Original,Sunrise,Action,Bones,1.0,False,164,449,197791,776,120243,8.41
2,6,Trigun,Manga,Victor Entertainment,Action,Madhouse,26.0,False,255,146,408548,10432,212537,8.30
3,7,Witch Hunter Robin,Original,Bandai Visual,Action,Sunrise,26.0,False,2371,1171,79397,537,32837,7.33
4,8,Bouken Ou Beet,Manga,TV Tokyo,Adventure,Toei Animation,52.0,False,3544,3704,11708,14,4894,7.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13626,39189,Te Ke Dong Ji Pian,Unknown,NaN,Action,NaN,54.0,False,13301,15461,7,0,0,NaN
13627,39190,Wang Zhe Wai Chuan,Unknown,NaN,Comedy,NaN,12.0,False,13570,15472,7,0,0,NaN
13628,39191,Wan Jie Shen Zhu,Unknown,NaN,Fantasy,NaN,60.0,False,13568,15470,7,0,0,NaN
13629,39192,Xia Gu Zhong An Zu,Unknown,NaN,Fantasy,NaN,12.0,False,13635,15473,7,0,0,NaN
13630,39197,Karrimor Mountain Club,Original,NaN,Adventure,NaN,4.0,False,11624,15424,10,0,0,NaN

In [36]:
df.head()

,animeID,name,source,producers,genre,studio,episodes,airing,rank,popularity,members,favorites,reviewers,Animation_score
0,1,Cowboy Bebop,Original,Bandai Visual,Action,Sunrise,26.0,False,26,39,795733,43460,405664,8.81
1,5,Cowboy Bebop: Tengoku no Tobira,Original,Sunrise,Action,Bones,1.0,False,164,449,197791,776,120243,8.41
2,6,Trigun,Manga,Victor Entertainment,Action,Madhouse,26.0,False,255,146,408548,10432,212537,8.30
3,7,Witch Hunter Robin,Original,Bandai Visual,Action,Sunrise,26.0,False,2371,1171,79397,537,32837,7.33
4,8,Bouken Ou Beet,Manga,TV Tokyo,Adventure,Toei Animation,52.0,False,3544,3704,11708,14,4894,7.03

In [61]:
df.describe()

,animeID,episodes,rank,popularity,members,favorites,reviewers,Animation_score
count,13631.000000,13349.000000,13631.000000,13631.000000,1.363100e+04,13631.000000,1.363100e+04,13518.000000
mean,19115.689238,12.704173,6936.692099,7853.461228,2.688763e+04,366.201746,1.340632e+04,6.294161
std,13561.015465,52.352845,3992.674468,4642.148157,8.666043e+04,2992.729277,4.950832e+04,1.099974
min,1.000000,1.000000,1.000000,1.000000,6.000000e+00,0.000000,0.000000e+00,1.000000
25%,5538.500000,1.000000,3477.000000,3578.000000,2.150000e+02,0.000000,4.600000e+01,5.590000
50%,18857.000000,1.000000,6949.000000,8128.000000,1.405000e+03,2.000000,4.370000e+02,6.380000
75%,32844.500000,12.000000,10422.000000,11992.500000,1.294200e+04,24.000000,4.970000e+03,7.100000
max,39197.000000,3057.000000,13838.000000,15474.000000,1.610561e+06,120331.000000,1.107955e+06,10.000000

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13631 entries, 0 to 13630
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   animeID          13631 non-null  int64
 1   name             13631 non-null  object
 2   source           13631 non-null  object
 3   producers        7414 non-null   object
 4   genre            13569 non-null  object
 5   studio           8369 non-null   object
 6   episodes         13349 non-null  float64
 7   airing           13631 non-null  bool
 8   rank             13631 non-null  int64
 9   popularity       13631 non-null  int64
 10  members          13631 non-null  int64
 11  favorites        13631 non-null  int64
 12  reviewers        13631 non-null  int64
 13  Animation_score  13518 non-null  float64
dtypes: bool(1), float64(2), int64(6), object(5)
memory usage: 1.4+ MB

In [44]:
df.iloc[2]

animeID                               6
name                             Trigun
source                            Manga
producers          Victor Entertainment
genre                            Action
studio                         Madhouse
episodes                           26.0
airing                            False
rank                                255
popularity                          146
members                          408548
favorites                         10432
reviewers                        212537
Animation_score                     8.3
Name: 2, dtype: object

In [53]:
df.loc[2]['name']

'Trigun'

In [54]:
df['episodes'].count()

13349

In [55]:
# def extract_episode(txt):
#     check =False
#     data=""
#     for i in txt:
#         if i == ')':
#             check=False
#             return data
#         if check ==True:
#             data=data+i
#         if i== '(':
#             check=True
    
# df['name'].apply(extract_episode)

In [58]:
df['producers'].astype(str)

0               Bandai Visual
1                     Sunrise
2        Victor Entertainment
3               Bandai Visual
4                    TV Tokyo
                 ...
13626                     nan
13627                     nan
13628                     nan
13629                     nan
13630                     nan
Name: producers, Length: 13631, dtype: object

In [60]:
df.isnull().sum()

animeID               0
name                  0
source                0
producers          6217
genre                62
studio             5262
episodes            282
airing                0
rank                  0
popularity            0
members               0
favorites             0
reviewers             0
Animation_score     113
dtype: int64

In [63]:
df['episodes']=df['episodes'].fillna(df['episodes'].mean())
df['Animation_score']=df['Animation_score'].fillna(df['Animation_score'].mean())


df['producers']=df['producers'].fillna(df['producers'].mode()[0])
df['genre']=df['genre'].fillna(df['genre'].mode()[0])
df['studio']=df['studio'].fillna(df['studio'].mode()[0])

In [64]:
df['producers'].astype(str)

0               Bandai Visual
1                     Sunrise
2        Victor Entertainment
3               Bandai Visual
4                    TV Tokyo
                 ...
13626                     NHK
13627                     NHK
13628                     NHK
13629                     NHK
13630                     NHK
Name: producers, Length: 13631, dtype: object

In [ ]:
df1['genre'].unique()
df1['genre'].map({'Action':0,'Adventure':1})

In [65]:
df['genre'].unique()
df['genre'].map({'Action':0,'Adventure':1})

0        0.0
1        0.0
2        0.0
3        0.0
4        1.0
        ...
13626    0.0
13627    NaN
13628    NaN
13629    NaN
13630    1.0
Name: genre, Length: 13631, dtype: float64

In [3]:
print("*******************************************************")
print("\nSOHEL KHAN")
print("*******************************************************")
candy=15
n=int(input("How many candy do you  want"))
for i in range(1,n+1):
    if candy>0:
        print("candy",i)
        candy-=1
    else:
        print("candy out of stock")
        break
print("Remaining candy",candy)

*******************************************************

SOHEL KHAN
*******************************************************
candy 1
candy 2
candy 3
candy 4
candy 5
candy 6
candy 7
candy 8
candy 9
candy 10
candy 11
candy 12
candy 13
candy 14
candy 15
candy out of stock
Remaining candy 0

In [58]:
print("********************************")
print("\tSohel shop")
print("********************************")
candy=10
n=int(input("How many candy do you want:"))
for i in range(1,n+1):
    if candy>0:
        print("candy",i)
        candy-=1
    else:
        print("Out of stock")
        break
print("remzning candy",candy)

********************************
	Sohel shop
********************************
candy 1
candy 2
candy 3
candy 4
candy 5
remzning candy 5

In [45]:
print("********************************")
print("\tSohel shop")
print("********************************")
candy=10
n=int(input("How many candy do you want:"))
for i in range(1,min(n,candy)+1):

    candy-=1
    print("candy",i,candy)
    
if n>10:
    print("out of stock")
    
else:
    print("Remaning candies :",candy)

********************************
	Sohel shop
********************************
candy 1 9
candy 2 8
candy 3 7
candy 4 6
candy 5 5
candy 6 4
candy 7 3
candy 8 2
candy 9 1
Remaning candies : 1

In [53]:
print("********************************")
print("\tSohel Shop")
print("********************************")
candy=10
n=int(input("How many candies do you want: "))
for i in range(1,n+1):
    if candy>0:
        print("candy",i)
        candy-=1
    else:
        print("Out of stock")
        break
print("Remaining Candidates :",candy)

********************************
	Sohel Shop
********************************
candy 1
candy 2
candy 3
candy 4
candy 5
candy 6
candy 7
candy 8
candy 9
candy 10
Out of stock
Remaining Candidates : 0

In [51]:
print("********************************")
print("\tSohel Shop")
print("********************************")

candy = 10
n = int(input("How many candies do you want: "))

for i in range(1, n + 1):

    if candy > 0:
        print("Candy", i)
        candy = candy - 1
    else:
        print("Out of stock")
        break

print("Remaining candies:", candy)

********************************
	Sohel Shop
********************************
Candy 1
Candy 2
Candy 3
Candy 4
Candy 5
Candy 6
Candy 7
Candy 8
Candy 9
Remaining candies: 1

PRACTICE QUESTION

In [ ]:
# 🔥 Basic Programming / Logic Questions
# Prime Number

n=1

if n<=1:
    print("not prime")
else:
    for i in range(2,n):
        if n%i==0:
            print(" not prime")
            break
    else:
        print("prime")

not prime

In [ ]:
# Composite Number
n=int(input("Enter a num"))
if n<=1:
    print("neither prime nor composite")
else:
    for i in range(2,n):
        if n%i==0:
            print("Composite Num ")
            break
    else:
        print("prime")

prime

In [24]:
# Sum of Digits
n=int(input("Enter a num:"))
sum=0
while n>0:
    r=n%10
    sum+=r
    n//=10
sum

15

In [25]:
# Reverse a Number
n=int(input("Enter  a num:"))
rev=0
while n>0:
    r=n%10
    rev=rev*10+r
    n//=10
rev

54321

In [29]:
# Palindrome Number
n=int(input("Enter  a num:"))
s=n
rev=0
while n>0:
    r=n%10
    rev=rev*10+r
    n//=10
if s==rev:
    print("Palindrom")
else:
    print("Not a palindrom")

Not a palindrom

In [37]:
# Palindrome String
s="sohosds"
left,right=0,len(s)-1
while left<right:
    if not s[left].isalnum():
        left+=1
    elif not s[right].isalnum():
        right-=1
    elif s[left].lower()!=s[right].lower():
        print("Not palindrom")
        break
    else:
        left+=1
        right-=1
else:

    print("Plindrom")

Not palindrom

In [46]:
# Count Vowels in String
vowels="aeiouAEIOU"
string='sohel'
cnt=0
for i in string:
   if i in vowels :
      cnt+=1
cnt

2

In [48]:
# Reverse a String
s="python"
print(s[::-1])

nohtyp

In [50]:
# Multiplication Table
s=int(input("Enter a tabel"))

for i in range(1,11):
    print(s,"*",i,"=",s*i)

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

In [57]:
# Factorial of a Number
n=int(input("Enter a num"))
mul=1
for i in range(n,0,-1):
    mul*=i
mul

2

In [70]:
# Fibonacci Series
n=int(input("Enter a num"))
if n==0:
    print('0')
elif n==1:
    print('1')
else:
    a,b=0,1
    for i in range(2,n+1):
        a,b=b,a+b
        print(b,end=" ")

1 2 3

In [73]:
# Even and Odd
n=int(input("Enter  a num"))
if n%2==0:
    print("Even")
else:
    print("Odd")

Odd

In [6]:
# Largest of Three Numbers
a=int(input("Enter a num1"))
b=int(input("Enter a num2"))
c=int(input("Enter a num3"))
if a > b and a > c:
    print("a is greater")
elif b>a and b>c:
    print("b is greater")
else:
    print("c is greater")

a is greater

In [8]:
# Second Largest Number
lst=[10,8,9,7,1]
if lst[0]>lst[1]:
    max1=lst[0]
    max2=lst[1]
else:
    max1=lst[1]
    max2=lst[0]
for i in range(2,len(lst)):
    if lst[i]>max1:
        max2=max1
        max1=lst[0]
    elif lst[i]>max2 and i!=max1:
        max2=lst[i]
max2
max1

10

In [10]:
# Count Digits
n=int(input("Enter a num"))
cnt=0
while n>0:
    n//=10
    cnt+=1
cnt

6

In [19]:
n=5
for i in range(1,n+1):
    for j in range(i):
        print("*",end=" ")
    print()

*
* *
* * *
* * * *
* * * * *

In [20]:
n=5
for i in range(n,0,-1):
    for j in range(i):
        print("*",end=" ")
    print()

* * * * *
* * * *
* * *
* *
*

In [22]:
n=5
for i in range(1,n+1):
    for j in range(i):
        print(i,end=" ")
    print()

1
2 2
3 3 3
4 4 4 4
5 5 5 5 5