In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {'creatures': ['Eagles', 'Eagles', 'Ducks', 'Herons', 'Herons',
'Eagles', 'Ducks', 'Eagles', 'Herons', 'Herons', 'Eagles'],
 'weight': [2.0, 5, 3.0, np.nan, 7, 2.5, 6, np.nan, 9, 3, 2.0],
 'frequency': [1, 3, 2, 5, 2, 3, 1, 3, 4, 2, 1],
 'status': ['no', 'no', 'yes', np.nan, 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
'no'],
 'height': [1.2, 2.5, 1.8, 3.0, 2.2, 1.9, 2.6, 1.4, 2.8, 2.3, 1.1],
 'region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North', 'East', 'South'],
 'danger_level': ['low', 'medium', 'high', 'low', 'high', 'medium',
'high', 'low', 'medium', 'high', 'low']}
labels = ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p']

I. Write a program to create a DataFrame named df from the
above dictionary data, using labels as the index.

In [5]:
pd.DataFrame(data,index=labels)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [7]:
df=pd.DataFrame(data,labels)
df

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

II. Write a program to display the basic information of the
DataFrame, including its summary statistics and data types.

In [11]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, x to p
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   creatures     11 non-null     object
 1   weight        9 non-null      float64
 2   frequency     11 non-null     int64
 3   status        10 non-null     object
 4   height        11 non-null     float64
 5   region        11 non-null     object
 6   danger_level  11 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1004.0+ bytes

         weight  frequency     height
count  9.000000  11.000000  11.000000
mean   4.388889   2.454545   2.072727
std    2.497221   1.293340   0.646670
min    2.000000   1.000000   1.100000
25%    2.500000   1.500000   1.600000
50%    3.000000   2.000000   2.200000
75%    6.000000   3.000000   2.550000
max    9.000000   5.000000   3.000000

In [12]:
df.dtypes

creatures        object
weight          float64
frequency         int64
status           object
height          float64
region           object
danger_level     object
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, x to p
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   creatures     11 non-null     object
 1   weight        9 non-null      float64
 2   frequency     11 non-null     int64
 3   status        10 non-null     object
 4   height        11 non-null     float64
 5   region        11 non-null     object
 6   danger_level  11 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 704.0+ bytes

In [5]:
# summry satstics mean descrbe

df.describe()

         weight  frequency     height
count  9.000000  11.000000  11.000000
mean   4.388889   2.454545   2.072727
std    2.497221   1.293340   0.646670
min    2.000000   1.000000   1.100000
25%    2.500000   1.500000   1.600000
50%    3.000000   2.000000   2.200000
75%    6.000000   3.000000   2.550000
max    9.000000   5.000000   3.000000

In [6]:
df.dtypes

creatures        object
weight          float64
frequency         int64
status           object
height          float64
region           object
danger_level     object
dtype: object

III. Write a program to display every alternate row of the
DataFrame (starting from index 0)

In [14]:
df.iloc[::2]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
t     Ducks     6.0          1    yes     2.6   East         high
r    Herons     9.0          4    yes     2.8  North       medium
p    Eagles     2.0          1     no     1.1  South          low

In [7]:
df

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [8]:
df[::2]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
t     Ducks     6.0          1    yes     2.6   East         high
r    Herons     9.0          4    yes     2.8  North       medium
p    Eagles     2.0          1     no     1.1  South          low

In [9]:
# iloc mean a location based oindexing use
df.iloc[::2]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
t     Ducks     6.0          1    yes     2.6   East         high
r    Herons     9.0          4    yes     2.8  North       medium
p    Eagles     2.0          1     no     1.1  South          low

IV. Write a program to display only rows at index positions 1st,
3rd, and 7th from columns creatures and weight of the
DataFrame

In [19]:
df.iloc[[1,3,7] ,[0,1]]

  creatures  weight
y    Eagles     5.0
w    Herons     NaN
s    Eagles     NaN

In [10]:
df.iloc[[0,3,7],[0,1]]

  creatures  weight
x    Eagles     2.0
w    Herons     NaN
s    Eagles     NaN

V. Write a program to select and display the rows where the
frequency is less than 4.

In [22]:
df[df['frequency']<4]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [11]:
df

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [12]:
result=df[df['frequency'] < 4]

In [13]:
result

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

VI. Write a program to select and display all rows where there are
NaN values in the columns weight or status.

In [28]:
result=df[df['weight'].isna() |df['status'].isna()]
result

  creatures  weight  frequency status  height region danger_level
w    Herons     NaN          5    NaN     3.0   West          low
s    Eagles     NaN          3     no     1.4   West          low

In [14]:
df

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [15]:
result=df[df['weight'].isna() | df['status'].isna()]

In [16]:
result

  creatures  weight  frequency status  height region danger_level
w    Herons     NaN          5    NaN     3.0   West          low
s    Eagles     NaN          3     no     1.4   West          low

VII. Write a program to fill the NaN values in the DataFrame with
the mode (most frequent value) of the respective columns.

In [33]:
mode_v=df['weight'].mode()[1]
mode_v
df.fillna(mode_v)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     3.0          5    3.0     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     3.0          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [17]:
print(df)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [18]:
mod_value=df['weight'].mode()[1]
print(mod_value)
df.fillna(mod_value)

3.0

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     3.0          5    3.0     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     3.0          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

 VIII.	Write a program to find the total number of frequency visits for the bird 'Herons'.

In [37]:
df
df.loc[df['creatures']=='Herons','frequency'].sum()

np.int64(13)

In [19]:
print(df)
df.loc[df['creatures']=='Herons','frequency'].sum()

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

np.int64(13)

IX.	Write a program to count and display the number of each type of creature in the DataFrame.

In [20]:
df['creatures'].value_counts()

creatures
Eagles    5
Herons    4
Ducks     2
Name: count, dtype: int64

In [21]:
df['creatures'].count()

np.int64(11)

 
X.	Write a program to remove duplicate rows from the DataFrame df permanently. Display the DataFrame after the changes.

In [22]:
print(df)
df.drop_duplicates(inplace=True)
print(df)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low
  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low


XI.	Write a program to replace the status of 'no' to 'not available' for all occurrences in the DataFrame df.

In [40]:
df['status'].replace('no','not Available')

x    not Available
y    not Available
z              yes
w              NaN
v              yes
u              yes
t              yes
s    not Available
r              yes
q              yes
p    not Available
Name: status, dtype: object

In [23]:
df

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [34]:
df1=df['status'].replace('no','not availabe')
df1

x    not availabe
y    not availabe
z             yes
w             NaN
v             yes
u             yes
t             yes
s    not availabe
r             yes
q             yes
p    not availabe
Name: status, dtype: object

XII.	Write a program to add a new column size to the DataFrame df, where the values are based on the height column: label any bird taller than 2.5 as 'Large', otherwise label as 'Small'.

In [55]:
df['size']=np.where(df['height']> 2.5,'Large','Small')
print(df['size'])
print(df)

x    Small
y    Small
z    Small
w    Large
v    Small
u    Small
t    Large
s    Small
r    Large
q    Small
p    Small
Name: size, dtype: object
  creatures  weight  frequency        status  height region danger_level  \
x    Eagles     2.0          1  not availabe     1.2  North          low
y    Eagles     5.0          3  not availabe     2.5  South       medium
z     Ducks     3.0          2           yes     1.8   East         high
w    Herons     NaN          5           NaN     3.0   West          low
v    Herons     7.0          2           yes     2.2  North         high
u    Eagles     2.5          3           yes     1.9  South       medium
t     Ducks     6.0          1           yes     2.6   East         high
s    Eagles     NaN          3  not availabe     1.4   West          low
r    Herons     9.0          4           yes     2.8  North       medium
q    Herons     3.0          2           yes     2.3   East         high
p    Eagles     2.0          1  not availabe     1.1  South          low

    size weight_size
x  Small       False
y  Small        True
z  Small       False
w  Large       False
v  Small        True
u  Small       False
t  Large        True
s  Small       False
r  Large        True
q  Small       False
p  Small       False

In [ ]:
# were ka use hum  condition lagana ka liya karta ha
df['weight_size']=np.where(df['weight']>3.0,'True','False')
print(df['weight_size'])
print(df)

x    False
y     True
z    False
w    False
v     True
u    False
t     True
s    False
r     True
q    False
p    False
Name: weight_size, dtype: object
  creatures  weight  frequency        status  height region danger_level  \
x    Eagles     2.0          1  not availabe     1.2  North          low
y    Eagles     5.0          3  not availabe     2.5  South       medium
z     Ducks     3.0          2           yes     1.8   East         high
w    Herons     NaN          5           NaN     3.0   West          low
v    Herons     7.0          2           yes     2.2  North         high
u    Eagles     2.5          3           yes     1.9  South       medium
t     Ducks     6.0          1           yes     2.6   East         high
s    Eagles     NaN          3  not availabe     1.4   West          low
r    Herons     9.0          4           yes     2.8  North       medium
q    Herons     3.0          2           yes     2.3   East         high
p    Eagles     2.0          1  not availabe     1.1  South          low

    size weight_size
x  Small       False
y  Small        True
z  Small       False
w  Large       False
v  Small        True
u  Small       False
t  Large        True
s  Small       False
r  Large        True
q  Small       False
p  Small       False

XIII.	Write a program to sort the DataFrame df by danger_level and height in descending order.

In [44]:
s=df.sort_values(by=['danger_level','height'],ascending=[False,False])
s

  creatures  weight  frequency status  height region danger_level
r    Herons     9.0          4    yes     2.8  North       medium
y    Eagles     5.0          3     no     2.5  South       medium
u    Eagles     2.5          3    yes     1.9  South       medium
w    Herons     NaN          5    NaN     3.0   West          low
s    Eagles     NaN          3     no     1.4   West          low
x    Eagles     2.0          1     no     1.2  North          low
p    Eagles     2.0          1     no     1.1  South          low
t     Ducks     6.0          1    yes     2.6   East         high
q    Herons     3.0          2    yes     2.3   East         high
v    Herons     7.0          2    yes     2.2  North         high
z     Ducks     3.0          2    yes     1.8   East         high

In [ ]:
# by parameter batata ha ki kis column ya kis parameter ka sath sort karna ha 
# df=df.sort_values(by=['danger_level','height'],ascending=[False,False])
# df

,creatures,weight,frequency,status,height,region,danger_level,size,weight_size
r,Herons,9.0,4,yes,2.8,North,medium,Large,True
y,Eagles,5.0,3,not availabe,2.5,South,medium,Small,True
u,Eagles,2.5,3,yes,1.9,South,medium,Small,False
w,Herons,NaN,5,NaN,3.0,West,low,Large,False
s,Eagles,NaN,3,not availabe,1.4,West,low,Small,False
x,Eagles,2.0,1,not availabe,1.2,North,low,Small,False
p,Eagles,2.0,1,not availabe,1.1,South,low,Small,False
t,Ducks,6.0,1,yes,2.6,East,high,Large,True
q,Herons,3.0,2,yes,2.3,East,high,Small,False
v,Herons,7.0,2,yes,2.2,North,high,Small,True
z,Ducks,3.0,2,yes,1.8,East,high,Small,False

XIV.	Write a program to reset the index of the DataFrame df to the default integer index, without affecting the original index.

In [79]:
df

,creatures,weight,frequency,status,height,region,danger_level,size,weight_size
r,Herons,9.0,4,yes,2.8,North,medium,Large,True
y,Eagles,5.0,3,not availabe,2.5,South,medium,Small,True
u,Eagles,2.5,3,yes,1.9,South,medium,Small,False
w,Herons,NaN,5,NaN,3.0,West,low,Large,False
s,Eagles,NaN,3,not availabe,1.4,West,low,Small,False
x,Eagles,2.0,1,not availabe,1.2,North,low,Small,False
p,Eagles,2.0,1,not availabe,1.1,South,low,Small,False
t,Ducks,6.0,1,yes,2.6,East,high,Large,True
q,Herons,3.0,2,yes,2.3,East,high,Small,False
v,Herons,7.0,2,yes,2.2,North,high,Small,True
z,Ducks,3.0,2,yes,1.8,East,high,Small,False

In [81]:
reset_index=df.reset_index()
reset_index

,index,creatures,weight,frequency,status,height,region,danger_level,size,weight_size
0,r,Herons,9.0,4,yes,2.8,North,medium,Large,True
1,y,Eagles,5.0,3,not availabe,2.5,South,medium,Small,True
2,u,Eagles,2.5,3,yes,1.9,South,medium,Small,False
3,w,Herons,NaN,5,NaN,3.0,West,low,Large,False
4,s,Eagles,NaN,3,not availabe,1.4,West,low,Small,False
5,x,Eagles,2.0,1,not availabe,1.2,North,low,Small,False
6,p,Eagles,2.0,1,not availabe,1.1,South,low,Small,False
7,t,Ducks,6.0,1,yes,2.6,East,high,Large,True
8,q,Herons,3.0,2,yes,2.3,East,high,Small,False
9,v,Herons,7.0,2,yes,2.2,North,high,Small,True
10,z,Ducks,3.0,2,yes,1.8,East,high,Small,False

XV.	Write a program to create a new DataFrame df_copy by selecting only the rows where weight is greater than 5, and include only the columns creatures, weight, and region.

In [88]:
df_copy=df.loc[df['weight']>5,['creatures','weight','region']]
df_copy

  creatures  weight region
r    Herons     9.0  North
t     Ducks     6.0   East
v    Herons     7.0  North

In [45]:
df_copy=df.loc[df['weight']>5,['creatures','weight','region']]
df_copy

  creatures  weight region
v    Herons     7.0  North
t     Ducks     6.0   East
r    Herons     9.0  North