In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler,LabelEncoder

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset("tips")

In [3]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(1)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  243 non-null    float64
 1   tip         243 non-null    float64
 2   sex         243 non-null    category
 3   smoker      243 non-null    category
 4   day         243 non-null    category
 5   time        243 non-null    category
 6   size        243 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 9.1 KB

In [9]:
for i in df.select_dtypes(include='category'):
    print(df[i].unique())

['Female', 'Male']
Categories (2, object): ['Male', 'Female']
['No', 'Yes']
Categories (2, object): ['Yes', 'No']
['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']
['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [10]:
gender_encoder=LabelEncoder()
smoker_encoder=LabelEncoder()
day_encoder=LabelEncoder()
time_encoder=LabelEncoder()

df['sex']=gender_encoder.fit_transform(df['sex'])
df['smoker']=smoker_encoder.fit_transform(df['smoker'])
df['day']=day_encoder.fit_transform(df['day'])
df['time']=time_encoder.fit_transform(df['time'])

In [11]:
df

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[243 rows x 7 columns]

In [12]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [13]:
x=df[['total_bill','sex', 'smoker', 'day', 'time', 'size']]
y=df['tip']

In [14]:
x

     total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     0     2
1         10.34    1       0    2     0     3
2         21.01    1       0    2     0     3
3         23.68    1       0    2     0     2
4         24.59    0       0    2     0     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     0     3
240       27.18    0       1    1     0     2
241       22.67    1       1    1     0     2
242       17.82    1       0    1     0     2
243       18.78    0       0    3     0     2

[243 rows x 6 columns]

In [15]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 243, dtype: float64

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit_transform(x_test)

In [20]:
from sklearn.metrics import r2_score
training_acc=[]
testing_acc=[]
for i in range(1,20,2):
    Knn=KNeighborsRegressor(n_neighbors=i,metric='minkowski',p=2)
    Knn.fit(x_train_scaled,y_train)
    y_train_pred=Knn.predict(x_train_scaled)
    y_pred=Knn.predict(x_test_scaled)
    training_acc.append(r2_score(y_train,y_train_pred))
    testing_acc.append(r2_score(y_test,y_pred))

In [21]:
for i , j in zip(training_acc,testing_acc):
    print(i,j)

1.0 0.17778760003928917
0.6084719167122152 0.24067509375450624
0.5790999945462676 0.31351221268132945
0.5326976542050242 0.2748570481461414
0.5041728288231415 0.357270576702862
0.47344902717884796 0.3338696200020377
0.4481837240446712 0.3499381228597592
0.40877346367349676 0.3534504753023763
0.4097063477758439 0.3453350239036068
0.39299961251810744 0.35864205303069785