In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("used-bikes.csv")

In [3]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand,Original Price
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS,82500
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield,230000
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph,1100000
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS,140000
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha,150000
...,...,...,...,...,...,...,...,...,...
7307,Hero Hunk Rear Disc 150cc,25000,Delhi,48587,First Owner,8,150,Hero,120000
7308,Bajaj Avenger 220cc,35000,Bangalore,60000,First Owner,9,220,Bajaj,160000
7309,Harley-Davidson Street 750 ABS,450000,Jodhpur,3430,First Owner,4,750,Harley-Davidson,630000
7310,Bajaj Dominar 400 ABS,139000,Hyderabad,21300,First Owner,4,400,Bajaj,245000
7311,Bajaj Avenger Street 220,80000,Hyderabad,7127,First Owner,5,220,Bajaj,160000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7312 entries, 0 to 7311
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bike_name       7312 non-null   object
 1   price           7312 non-null   object
 2   city            7312 non-null   object
 3   kms_driven      7312 non-null   int64
 4   owner           7312 non-null   object
 5   age             7312 non-null   int64
 6   power           7312 non-null   int64
 7   brand           7312 non-null   object
 8   Original Price  7312 non-null   int64
dtypes: int64(4), object(5)
memory usage: 514.3+ KB

In [5]:
df.describe()

          kms_driven          age        power  Original Price
count    7312.000000  7312.000000  7312.000000    7.312000e+03
mean    23949.871718     6.733862   228.496991    1.823393e+05
std     27340.904392     3.857574   158.035118    1.835454e+05
min         1.000000     1.000000   100.000000    5.000000e+04
25%     10148.500000     4.000000   125.000000    9.000000e+04
50%     19000.000000     6.000000   160.000000    1.500000e+05
75%     30396.750000     8.000000   350.000000    2.150000e+05
max    750000.000000    63.000000  1800.000000    2.750000e+06

In [6]:
df.isnull().sum()

bike_name         0
price             0
city              0
kms_driven        0
owner             0
age               0
power             0
brand             0
Original Price    0
dtype: int64

In [7]:

!pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (2.0.1)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (1.15.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in c:\users\hp\appdata\roaming\python\python312\site-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python312\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
df.info()
df1=df.select_dtypes(exclude='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7312 entries, 0 to 7311
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bike_name       7312 non-null   object
 1   price           7312 non-null   object
 2   city            7312 non-null   object
 3   kms_driven      7312 non-null   int64
 4   owner           7312 non-null   object
 5   age             7312 non-null   int64
 6   power           7312 non-null   int64
 7   brand           7312 non-null   object
 8   Original Price  7312 non-null   int64
dtypes: int64(4), object(5)
memory usage: 514.3+ KB

In [9]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand,Original Price
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS,82500
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield,230000
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph,1100000
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS,140000
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha,150000
...,...,...,...,...,...,...,...,...,...
7307,Hero Hunk Rear Disc 150cc,25000,Delhi,48587,First Owner,8,150,Hero,120000
7308,Bajaj Avenger 220cc,35000,Bangalore,60000,First Owner,9,220,Bajaj,160000
7309,Harley-Davidson Street 750 ABS,450000,Jodhpur,3430,First Owner,4,750,Harley-Davidson,630000
7310,Bajaj Dominar 400 ABS,139000,Hyderabad,21300,First Owner,4,400,Bajaj,245000
7311,Bajaj Avenger Street 220,80000,Hyderabad,7127,First Owner,5,220,Bajaj,160000

In [10]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Hero', 'Bajaj',
       'Suzuki', 'Benelli', 'Honda', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [11]:
df['city'].unique()

array(['Ahmedabad', 'Delhi', 'Bangalore', 'Mumbai', 'Kalyan', 'Faridabad',
       'Mettur', 'Hyderabad', 'Kaithal', 'Gurgaon', 'Pune', 'Noida',
       'Nashik', 'Kochi', 'Allahabad', 'Samastipur', 'Nadiad', 'Lucknow',
       'Jaipur', 'Karnal', 'Gorakhpur', 'Vidisha', 'Hosur', 'Bagalkot',
       'Baripara', 'Agra', 'Dharwad', 'Vadodara', 'Jalandhar', 'Surat',
       'Chennai', 'Navi Mumbai', 'Gandhidham', 'Visakhapatnam',
       'Thrissur', 'Kolkata', 'Ernakulam', 'Barasat', 'Ghaziabad',
       'Bhubaneshwar', 'Amritsar', 'Bhopal', 'Hamirpur(hp)', 'Kottayam',
       'Arrah', 'Patiala', 'Ranga Reddy', 'Mandi', 'Ludhiana', 'Mandya',
       'Siliguri', 'Aurangabad', 'Kanpur', 'Bhilwara', 'Meerut', 'Rewari',
       'Ahmednagar', 'Wardha', 'Chandigarh', 'Ranchi', 'Panvel', 'Thane',
       'Jabalpur', 'Kota', 'Rohtak', 'Rajkot', 'Varanasi', '24 Pargana',
       'Banka', 'Nagpur', 'Banki', 'Pali', 'Chhatarpur', 'Katihar',
       'Mohali', 'Rudrapur', 'Coimbatore', 'Jajpur', 'Mysore', 'Adoni',
       'Bikaner', 'Malout', 'Jammu', 'Rajnandgaon', 'Unnao', 'Godhara',
       'Kolhapur', 'Satara', 'Siwan', 'Dadra & Nagar Haveli', 'Bhiwani',
       'Koppal', 'Nizamabad', 'Madurai', 'Ujjain', 'Palakkad',
       'Tiruvallur', 'Panchkula', 'Nanjangud', 'Jhansi', 'Sonipat',
       'Puttur', 'Hoshiarpur', 'Gohana', 'Gautam Buddha Nagar',
       'Durgapur', 'Palwal', 'Chatrapur', 'Howrah', 'Jind', 'Hubli',
       'Panipat', 'Bharatpur', 'Vellore', 'Ambala', 'Guwahati', 'Gangtok',
       'Rajahmundry', 'Tiruchirappalli', 'Belgaum', 'Balaghat', 'Jatani',
       'Asansol', 'Bilaspur', 'Thanjavur', 'Raigarh(mh)', 'Mandi Dabwali',
       'Basti', 'Bolpur', 'Aligarh', 'Balrampur', 'Ratnagiri', 'Muktsar',
       'Baran', 'Haldwani', 'Thiruvananthapuram', 'Indore', 'Buxar',
       'Chaksu', 'Haridwar', 'Bharuch', 'Muvattupuzha', 'Patna',
       'Simdega', 'Singhbhum', 'Bardhaman', 'Pathankot', 'Kharar',
       'Silchar', 'Jhalawar', 'Roorkee', 'Saharanpur', 'Solapur',
       'Gwalior', 'Alibag', 'Katni', 'Khedbrahma', 'Valsad', 'Satna',
       'Hooghly', 'Gurdaspur', 'Dadri', 'Amravati', 'Durg', 'Mehsana',
       'Lansdowne', 'Cuttack', 'Jaisalmer', 'Hanumangarh', 'Dungarpur',
       'Sri Ganganagar', 'Margao', 'Chinsurah', 'Bhatinda', 'Sibsagar',
       'Khalilabad', 'Dehradun', 'Anand', 'Ankleshwar', 'Purnia',
       'Tiruverkadu', 'Bahadurgarh', 'Udaipur', 'Jodhpur', 'Sheikhpura',
       'Pondicherry', 'Sirsa', 'Godavari', 'Ajmer', 'Moradabad', 'Raipur',
       'Navsari', 'Herbertpur', 'Jamshedpur', 'Ramanagar', 'Berhampur',
       'Vijayawada', 'Murad Nagar', 'Chandrapur', 'Jamtara',
       'Uppidamangalam', 'Nalagarh', 'Una', 'Chakan', 'Idukki',
       'Shivpuri', 'Arkalgud', 'Bidar', 'Rupnagar', 'Deoghar',
       'Kanchipuram', 'Vapi', 'Medak', 'Kasargode', 'Dhanbad',
       'Dakshina Kannada', 'Ganaur', 'Jamalpur', 'Amraoti', 'Mangalore',
       'Deolali', 'Gandhinagar', 'Chitradurga', 'Chinchwad', 'Jhajjar',
       'Jagdalpur', 'Ranoli', 'Raiwala', 'Badarpur', 'Adalaj', 'Alipore',
       'Bhawani Mandi', 'Mughalsarai', 'Kollam', 'Farukhabad',
       'Thiruvallur', 'Udaipurwati', 'Rasra', 'Latur', 'Krishna',
       'Gangaikondan', 'Warangal', 'Uluberia', 'Poonamallee', 'Nagaon',
       'Hissar', 'Kanyakumari', 'Morbi', 'Bankura', 'Virar', 'Tikamgarh',
       'Sultanpur', 'Tirunelveli', 'Bihar Shariff', 'Goa-panaji',
       'Ganganagar', 'Kolar', 'Bahadurpur', 'Batala', 'Budhlada',
       'Muzaffarnagar', 'Adyar', 'Calicut', 'Raigarh', 'Sonepat',
       'Chikkaballapur', 'Kasba', 'Bulandshahr', 'Burdwan', 'Anjar',
       'Marandahalli', 'Badaun', 'Namakkal', 'Puri', 'Alwar',
       'Surendranagar', 'Khandela', 'Kullu', 'Mohammadabad', 'Sangareddy',
       'Ghazipur', 'Shimla', 'Azamgarh', 'Chenani', 'Kanpur Nagar',
       'Trivandrum', 'Secunderabad', 'Kurukshetra', 'Dhariawad',
       'Bargarh', 'Gadarpur', 'Chikamaglur', 'Karim Nagar', 'Kotdwar',
       'Jalaun', 'Parola', 'Bareilly', 'Salem', 'Indi', 'Muzaffarpur',
       'Nayagarh', 'Jalgaon', 'Ambikapur', 'Udupi', 'Junagadh',
       'Dibrugarh', 'Faridkot', 'Naraingarh', 'Karwar',
       'Sant Kabir Nagar', 'Viramgam', 'Manali', 'Gadwal', 'Honavar',
       'Mathura', 'Khandwa', 'Solan', 'Sitapur', 'Betul', 'Anantapur',
       'Sholapur', 'Pinjore', 'Qadian', 'Sangrur', 'Jorhat', 'Palanpur',
       'Narnaul', 'Palamu', 'Falakata', 'Ferozepur', 'Porbandar',
       'Dwarka', 'Rangpo', 'Cannanore (kannur)', 'Baghpat',
       'Jhumri Tilaiya', 'Naihati', 'Virudhunagar', 'Dharmavaram',
       'Darbhanga', 'Nawanshahr', 'Sangli', 'Suri', 'Yamuna Nagar',
       'Vasai', 'Aluva', 'Sirsi', 'Bijapur', 'Krishnagar', 'Bhiwadi',
       'Bellary', 'Erode', 'Aquem', 'Nellore', 'Udhampur', 'Dhamtari',
       'Vandalur', 'Motihari', 'Dharwar', 'Shimoga', 'Jhunjhunu',
       'Bijnor', 'Yemmiganur', 'Bokaro', 'Sambalpur', 'Kurnool',
       'Srinagar', 'Ranip', 'Davanagere', 'Rajouri', 'Begusarai',
       'Goregaon', 'Bally', 'Kachchh', 'Nagaur', 'Anekal', 'Nanded',
       'Dharamasala', 'Chhindwara', 'Jamnagar', 'Zirakpur', 'Abohar',
       'Barabanki', 'Nabha', 'Kadapa', 'Perumbavoor', 'Guntur',
       'Sundargarh', 'Nazira', 'Pratapgarh', 'Dharmapuri', 'Thangadh',
       'Lonavala', 'Vizianagaram', 'Kathua', 'Deesa', 'Tiruppur',
       'Gadchiroli', 'Gangaghat', 'Bhuj', 'Vastral', 'Phagwara', 'Kheda',
       'Swaimadhopur', 'Kharagpur', 'Jobner', 'Gondia', 'Bundi',
       'Hamirpur', 'Dongargaon', 'Mubarakpur', 'Tumkur', 'Sanand',
       'Kartarpur', 'Bhavnagar', 'Farrukhabad', 'Kadi', 'Seppa',
       'Challakere', 'Dhubri', 'Deoria', 'Akot', 'Alappuzha', 'Bhiwandi',
       'Shillong', 'Osmanabad', 'Kendua', 'Uran', 'Jaunpur', 'Hisar',
       'Bhubaneswar', 'Raiganj', 'Bhilai Nagar', 'Baloda', 'Anantnag',
       'Berhampore', 'Silvasa', 'Hospet', 'Palai', 'Sidhi'], dtype=object)

In [12]:
df1

      kms_driven  age  power  Original Price
0          17654    3    110           82500
1          11000    4    350          230000
2            110    8    675         1100000
3          16329    4    180          140000
4          10000    3    150          150000
...          ...  ...    ...             ...
7307       48587    8    150          120000
7308       60000    9    220          160000
7309        3430    4    750          630000
7310       21300    4    400          245000
7311        7127    5    220          160000

[7312 rows x 4 columns]

In [13]:

import pandas as pd
from statsmodels.api import add_constant
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [14]:
x=add_constant(df1)
x

      const  kms_driven  age  power  Original Price
0       1.0       17654    3    110           82500
1       1.0       11000    4    350          230000
2       1.0         110    8    675         1100000
3       1.0       16329    4    180          140000
4       1.0       10000    3    150          150000
...     ...         ...  ...    ...             ...
7307    1.0       48587    8    150          120000
7308    1.0       60000    9    220          160000
7309    1.0        3430    4    750          630000
7310    1.0       21300    4    400          245000
7311    1.0        7127    5    220          160000

[7312 rows x 5 columns]

In [15]:
vif =[variance_inflation_factor(x.values,i)for i in range(x.shape[1])]
vif

[np.float64(7.4261690872621005),
 np.float64(1.1595834935729148),
 np.float64(1.1541560575173342),
 np.float64(3.5343884158554757),
 np.float64(3.51352125831048)]

In [16]:
for features,i in zip(x,colmns[1:],vif[1:]):
    print(features,":",i)

NameError: name 'colmns' is not defined

In [ ]:
y=x['price']
x=x.drop('price',axis=1)

In [ ]:
import statsmodels.api as sm
model = sm.OLS(y,x).fit()

In [ ]:
print(model.summary())